import subprocess, unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

class FrontendSessionTests(unittest.TestCase):
    def test_session_restart_and_stale_event_isolation(self):
        html = (ROOT / "src" / "voice_workflow_agent" / "static" / "index.html").read_text(encoding="utf-8")
        script = html.split("<script>", 1)[1].split("</script>", 1)[0]
        self.assertNotIn("create"+"ScriptProcessor", script)
        self.assertNotIn("Script"+"ProcessorNode", script)
        self.assertNotIn("on"+"audioprocess", script)
        self.assertIn('audioWorklet.addModule("/mic-capture-worklet.js")',script)
        self.assertIn('numberOfOutputs:0',script)
        for constraint in (
            '"echoCancellation"',
            '"noiseSuppression"',
            '"autoGainControl"',
        ):
            self.assertIn(constraint,script)
        self.assertIn("마이크 음성 신호 감지됨", script)
        harness = r"""
const assert=(ok,message)=>{if(!ok)throw new Error(message)};
class Element{constructor(){this.children=[];this.fields={};this.textContent="";this.disabled=false;this.hidden=false;this.removed=false;this.dataset={};this.options=[]}set innerHTML(v){for(const c of ["transcript","reply","turn-status","filler-status","tools","turn-visual","stats","error"]){const item=new Element();item.textContent=c==="transcript"?"듣는 중…":"";this.fields[c]=item}}querySelector(s){return this.fields[s.slice(1)]}prepend(n){this.children.unshift(n)}replaceChildren(){this.children=[];this.options=this.children}appendChild(n){this.children.push(n);this.options=this.children}remove(){this.removed=true}addEventListener(){}setAttribute(){}}
const ids=Object.fromEntries(["start","stop","log","status","state","last-report-id","last-report-state","pending-report","language-status","language-mode","manual-language","pipeline-mode","protocol-id","protocol-pdf","register-protocol","protocol-upload-status","protocol-readiness","protocol-revision","session-configuration-status","new-user","language-confirmation","procedure-title","procedure-meta","procedure-status","procedure-progress","procedure-step-title","procedure-instruction","procedure-warning","procedure-spoken-summary","repeat-step","next-step","voice-command-hint","procedure-visual","source-visual-state","source-filename","source-page-number","source-short-hash","voice-processing","voice-filler-status","voice-primary-status","procedure-source","procedure-timer","procedure-observation","procedure-handoff","procedure-audit"].map(x=>[x,new Element()]));
ids["language-mode"].value="manual";ids["manual-language"].value="ko";ids["pipeline-mode"].value="cascade";ids["protocol-id"].value="candidate-a-curated-development-v1";
globalThis.document={getElementById:id=>ids[id],createElement:()=>new Element()}; globalThis.location={protocol:"http:",host:"test"};
class WS{static OPEN=1;static CLOSING=2;constructor(){this.readyState=1;this.sent=[]}send(x){this.sent.push(x)}close(){this.readyState=3}}
globalThis.WebSocket=WS; Object.defineProperty(globalThis,"navigator",{value:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[]})}},configurable:true}); globalThis.AudioContext=class{};
""" + script + r"""
(async()=>{
renderState("IDLE");assert(visibleState==="IDLE"&&!ids.start.disabled&&ids.stop.disabled,"initial controls");
let modulePath=null,sourceTarget=null,workletNode=null,trackStopped=false,requestedConstraints=null;Object.defineProperty(globalThis,"navigator",{value:{mediaDevices:{getSupportedConstraints:()=>({echoCancellation:true,noiseSuppression:true,autoGainControl:true}),getUserMedia:async constraints=>(requestedConstraints=constraints,{getTracks:()=>[{stop(){trackStopped=true}}]})}},configurable:true});globalThis.AudioContext=class{constructor(){this.sampleRate=48000;this.destination={};this.state="running";this.audioWorklet={addModule:async path=>{modulePath=path}}}createMediaStreamSource(){return{connect(node){sourceTarget=node},disconnect(){}}}resume(){return Promise.resolve()}close(){this.state="closed";return Promise.resolve()}};globalThis.AudioWorkletNode=class{constructor(context,name,options){this.context=context;this.name=name;this.options=options;this.disconnected=false;this.port={onmessage:null,postMessage:()=>{}};workletNode=this}disconnect(){this.disconnected=true}};
sessionActive=true;pipelineMode="native";renderState("LISTENING");await ensureAudio(0);assert(requestedConstraints.audio.channelCount===1&&requestedConstraints.audio.echoCancellation===true&&requestedConstraints.audio.noiseSuppression===true&&requestedConstraints.audio.autoGainControl===true,"supported microphone preprocessing not requested");assert(modulePath==="/mic-capture-worklet.js"&&workletNode.name==="voice-workflow-mic-capture"&&workletNode.options.numberOfOutputs===0&&sourceTarget===workletNode,"AudioWorklet graph invalid");const loud=new Float32Array(960);loud.fill(.1);workletNode.port.onmessage({data:loud.buffer});assert(micSignalSeen&&ids.status.textContent.includes("마이크 음성 신호 감지됨"),"browser mic signal not diagnosed");const sentPcm=socket.sent.at(-1);assert(sentPcm instanceof ArrayBuffer&&sentPcm.byteLength===960,"native PCM was not resampled to 24 kHz int16");const firstNode=workletNode;await ensureAudio(0);assert(workletNode===firstNode,"duplicate worklet node created");sessionActive=false;await closeAudio();assert(trackStopped&&firstNode.disconnected&&firstNode.port.onmessage===null,"microphone resources not cleaned");socket=new WS();sessionActive=true;pipelineMode="cascade";let fallbackConstraints=null;navigator.mediaDevices.getSupportedConstraints=()=>({});navigator.mediaDevices.getUserMedia=async constraints=>(fallbackConstraints=constraints,{getTracks:()=>[]});await ensureAudio(0);assert(fallbackConstraints.audio.channelCount===1&&!('echoCancellation' in fallbackConstraints.audio)&&!('noiseSuppression' in fallbackConstraints.audio)&&!('autoGainControl' in fallbackConstraints.audio),"unsupported optional constraints were made mandatory");const cascadeNode=workletNode,cascadeBlock=new Float32Array(960);cascadeNode.port.onmessage({data:cascadeBlock.buffer});const cascadePcm=socket.sent.at(-1);assert(cascadePcm instanceof ArrayBuffer&&cascadePcm.byteLength===640,"cascade PCM is not a 20 ms 16 kHz mono frame");sessionActive=false;await closeAudio();assert(cascadeNode.disconnected,"repeated microphone stop did not clean worklet");renderState("IDLE");
const oldSocket=socket;await onMessage({data:JSON.stringify({type:"speech.start",turn_id:1})},0,oldSocket);await onMessage({data:JSON.stringify({type:"transcript",turn_id:1,text:"old question"})},0,oldSocket);await onMessage({data:JSON.stringify({type:"reply.delta",turn_id:1,text:"old answer"})},0,oldSocket);const oldNode=ids.log.children[0];
await stopSession();assert(visibleState==="IDLE"&&ids.log.children.length===1,"stop state or transcript");socket=new WS();let audioInitializations=0;ensureAudio=async()=>{audioInitializations++};await startSession();assert(visibleState==="CONNECTING"&&ids.start.disabled&&!ids.stop.disabled,"start not connecting");assert(ids.log.children.length===0&&turns.size===0,"start reset incomplete");
const requestedStart=JSON.parse(socket.sent.at(-1));assert(JSON.stringify(requestedStart)===JSON.stringify({type:"session.start",configuration_id:1,mode:"cascade",language:"ko",protocol_id:"candidate-a-curated-development-v1"}),"browser start payload shape changed");assert(audioInitializations===0&&!sessionActive,"microphone or session activated before server acknowledgement");
const newSocket=socket,generation=sessionGeneration;await onMessage({data:JSON.stringify({type:"session.ready",configuration_id:999,mode:"cascade",language:"ko",protocol_id:"candidate-a-curated-development-v1",revision_id:"fixture-test"})},generation,newSocket);assert(audioInitializations===0&&!sessionActive&&visibleState==="CONNECTING","stale acknowledgement made UI ready");await onMessage({data:JSON.stringify({type:"session.ready",configuration_id:1,mode:"cascade",language:"ko",protocol_id:"candidate-a-curated-development-v1",revision_id:"fixture-test"})},generation,newSocket);assert(audioInitializations===1&&sessionActive&&visibleState==="LISTENING","accepted configuration did not activate microphone and UI");assert(acceptedSessionConfiguration.protocol_id==="candidate-a-curated-development-v1"&&acceptedSessionConfiguration.revision_id==="fixture-test"&&ids["session-configuration-status"].textContent.includes("서버 확인 완료"),"accepted protocol configuration not rendered");await onMessage({data:JSON.stringify({type:"session.started",state:"IDLE",pipeline:"cascade"})},generation,newSocket);assert(visibleState==="LISTENING","legacy session.started changed readiness");pipelineMode="native";await onMessage({data:JSON.stringify({type:"native.ready",sample_rate:24000,reconnected:false})},generation,newSocket);assert(nativeReadyDetail==="Native 음성 세션이 준비되었습니다.","initial ready not retained");await onMessage({data:JSON.stringify({type:"native.configuration.updated"})},generation,newSocket);assert(!ids.status.textContent.includes("복구"),"configuration update mislabeled as reconnect");await onMessage({data:JSON.stringify({type:"native.input.started",sample_rate:24000,frame_bytes:4096})},generation,newSocket);assert(ids.status.textContent.includes("마이크 스트림 전송 중"),"native input acknowledgement missing");await onMessage({data:JSON.stringify({type:"native.error",code:"test_upstream_error"})},generation,newSocket);assert(ids.status.textContent.includes("test_upstream_error"),"native upstream error hidden");await onMessage({data:JSON.stringify({type:"native.ready",sample_rate:24000,reconnected:true})},generation,newSocket);assert(ids.status.textContent.includes("실제로 복구"),"real reconnect not shown");await onMessage({data:JSON.stringify({type:"turn.processing",turn_id:1})},generation,newSocket);assert(visibleState==="THINKING","processing not thinking");
const curated0={attached:true,protocol_id:"candidate-a-curated-development-v1",revision_id:"fixture-test",display_name:"In-gel digestion protocol for protein identification",development_only:true,readiness_status:"analysis_required",active:false,current_step_label:null,current_step_id:null,total_steps:25,at_final_step:false,block_reason:null,revision:0,source_page_refs:[],visual_assets:[],visual_status:"unavailable",critical_warning_texts:[],display_summary:null};
await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id:1,action:"attached",state:curated0})},generation,newSocket);assert(ids["procedure-title"].textContent===curated0.display_name&&ids["procedure-meta"].textContent.includes("개발용")&&ids["procedure-status"].textContent.includes("대기"),`attached curated fixture not rendered truthfully: ${ids["procedure-title"].textContent}|${ids["procedure-meta"].textContent}|${ids["procedure-status"].textContent}|${curatedStateRevision}|${JSON.stringify(acceptedSessionConfiguration)}|${generation}/${sessionGeneration}|${socket===newSocket}`);
const curated1={...curated0,active:true,current_step_label:"1",current_step_id:"step-1",revision:1};await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id:1,action:"start",state:curated1})},generation,newSocket);assert(ids["procedure-progress"].textContent.includes("1/25")&&ids["procedure-status"].textContent.includes("진행 중"),"active curated step not rendered");
const stale={...curated1,current_step_label:"25",current_step_id:"step-25",revision:0};await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id:1,action:"next",state:stale})},generation,newSocket);assert(curatedProtocolState.current_step_label==="1","stale curated revision overwrote current state");await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id:999,action:"next",state:{...curated1,current_step_label:"2",current_step_id:"step-2",revision:2}})},generation,newSocket);assert(curatedProtocolState.current_step_label==="1","wrong configuration curated state accepted");
await onMessage({data:JSON.stringify({type:"session.language_state",mode:"auto",language:null})},generation,newSocket);assert(ids["language-status"].textContent.includes("Automatic"),"auto state missing");
await onMessage({data:JSON.stringify({type:"session.turn_language_resolved",turn_id:1,language:"en"})},generation,newSocket);assert(ids["language-status"].textContent.includes("English"),"resolved language missing");
await onMessage({data:JSON.stringify({type:"session.language_confirmation_required",turn_id:1,reason:"language_unresolved",languages:["ko","en"]})},generation,newSocket);assert(ids["language-confirmation"].hidden===false&&!ids["language-status"].textContent.includes("source_path"),"confirmation missing");
ids["language-mode"].value="manual";ids["manual-language"].value="en";requestLanguageMode();assert(JSON.parse(newSocket.sent.at(-1)).mode==="manual"&&JSON.parse(newSocket.sent.at(-1)).language==="en","manual event invalid");assert(acknowledgedLanguageMode==="auto","manual state changed before ack");
await onMessage({data:JSON.stringify({type:"session.language_state",mode:"manual",language:"en"})},generation,newSocket);assert(acknowledgedLanguageMode==="manual"&&ids["manual-language"].hidden===false,"manual ack missing");
const ps={attached:true,procedure_id:"demo",title:"FICTIONAL NON-OPERATIONAL Demo",version:"1",status:"active",total_step_count:2,completed_step_count:0,current_step_number:1,current_step_id:"one",current_step_title:"One",approved_current_instruction:"Approved fictional instruction."};
await onMessage({data:JSON.stringify({type:"procedure.state",state:ps})},generation,newSocket);assert(ids["procedure-title"].textContent===ps.title&&ids["procedure-instruction"].textContent===ps.approved_current_instruction,"procedure event not rendered");
const blocked={...ps,status:"blocked_for_handoff",handoff:{report_id:"SR-20260722-A1B2C3",blocked_step_id:"one"}};
await onMessage({data:JSON.stringify({type:"procedure.state",state:blocked})},generation,newSocket);assert(procedureState.status==="blocked_for_handoff"&&ids["procedure-status"].textContent.includes("진행 차단")&&ids["procedure-handoff"].textContent.includes("SR-20260722-A1B2C3"),"blocked workflow not rendered");
await onMessage({data:JSON.stringify({type:"procedure.state",state:ps})},generation,newSocket);
await onMessage({data:JSON.stringify({type:"reply.delta",turn_id:1,text:"completed step two"})},generation,newSocket);assert(procedureState.completed_step_count===0,"reply text mutated procedure");
await onMessage({data:JSON.stringify({type:"procedure.state",state:{attached:true,title:"bad"}})},generation,newSocket);assert(procedureState.completed_step_count===0,"malformed procedure state accepted");
for(const bad of [
 {...ps,current_step_number:2},
 {...ps,current_step_id:""},
 {...ps,completed_step_count:2},
 {...ps,status:"completed",completed_step_count:2},
 {...ps,status:"completed",completed_step_count:2,current_step_number:null,current_step_id:null,current_step_title:null,approved_current_instruction:"not null"}
]){await onMessage({data:JSON.stringify({type:"procedure.state",state:bad})},generation,newSocket);assert(procedureState.status==="active"&&procedureState.completed_step_count===0,"inconsistent procedure state accepted");}
const done={...ps,status:"completed",completed_step_count:2,current_step_number:null,current_step_id:null,current_step_title:null,approved_current_instruction:null};
await onMessage({data:JSON.stringify({type:"procedure.state",state:done})},generation,newSocket);assert(procedureState.status==="completed","canonical completed state rejected");
newUser();assert(JSON.parse(newSocket.sent.at(-1)).type==="session.reset","new user reset missing");
await onMessage({data:JSON.stringify({type:"procedure.state",state:{attached:false}})},generation,newSocket);assert(procedureState.attached===false&&ids["procedure-title"].textContent.includes("없음"),"procedure detach not rendered");
ids["language-mode"].value="auto";requestLanguageMode();assert(acknowledgedLanguageMode==="manual","request changed acknowledged mode");
await onMessage({data:JSON.stringify({type:"error",message:"invalid language mode"})},generation,newSocket);assert(ids["language-mode"].value==="manual"&&ids["manual-language"].value==="en"&&ids["language-status"].textContent.includes("Manual")&&ids["language-status"].textContent.includes("English"),"failed request did not roll back acknowledged language UI");assert(visibleState==="ERROR","failed request did not use safe error state");
const authoritativeDisplay="Full canonical development-fixture step instruction.";const shortSpeech="Short control acknowledgement.";await onMessage({data:JSON.stringify({type:"speech.start",turn_id:1})},generation,newSocket);await onMessage({data:JSON.stringify({type:"transcript",turn_id:1,text:"new question"})},generation,newSocket);await onMessage({data:JSON.stringify({type:"reply.delta",turn_id:1,text:authoritativeDisplay,speech_text:shortSpeech})},generation,newSocket);assert(turnNode(1,generation).querySelector(".reply").textContent===authoritativeDisplay+" "&&!turnNode(1,generation).querySelector(".reply").textContent.includes(shortSpeech),"curated display text was not rendered independently of speech text");
const draft={location:"Lab A",summary:"spill",urgency:"urgent",exposure_status:"unknown",material_or_equipment:"acetone"};
await onMessage({data:JSON.stringify({type:"tool.result",turn_id:1,tool:"create_safety_report",status:"awaiting_user_confirmation",report:draft})},generation,newSocket);assert(ids["pending-report"].hidden===false&&ids["pending-report"].textContent.includes("acetone"),"draft not visible");
await onMessage({data:JSON.stringify({type:"tool.call",turn_id:1,tool:"create_safety_report",status:"submitting",report:draft})},generation,newSocket);assert(ids["last-report-state"].textContent==="보고서 제출 중","submitting state missing");
await onMessage({data:JSON.stringify({type:"tool.result",turn_id:1,tool:"create_safety_report",status:"submission_failed",report:draft})},generation,newSocket);assert(ids["pending-report"].hidden===false&&ids["last-report-state"].textContent.includes("다시 승인하거나 취소"),"failed draft hidden");
await onMessage({data:JSON.stringify({type:"tool.result",turn_id:1,tool:"create_safety_report",status:"cancelled",report:draft})},generation,newSocket);assert(ids["pending-report"].hidden===true&&ids["last-report-id"].textContent==="아직 접수된 보고 없음","cancel did not reset draft UI");
await onMessage({data:JSON.stringify({type:"tool.result",turn_id:1,tool:"create_safety_report",status:"awaiting_user_confirmation",report:draft})},generation,newSocket);await onMessage({data:JSON.stringify({type:"tool.result",turn_id:1,tool:"create_safety_report",status:"confirmed",report:draft,report_id:"SR-20260722-A1B2C3",report_status:"queued_for_handoff",elapsed_ms:2})},generation,newSocket);const newNode=ids.log.children[0];assert(newNode!==oldNode&&newNode.querySelector(".transcript").textContent==="new question","transcript reset");assert(newNode.querySelector(".tools").textContent.includes("안전 보고 접수"),"tool result missing");assert(ids["last-report-id"].textContent==="SR-20260722-A1B2C3"&&ids["last-report-state"].textContent==="관리자 인계 대기"&&ids["pending-report"].hidden===true,"report card missing");
await onMessage({data:JSON.stringify({type:"report.status",report_id:"SR-20260722-A1B2C3",status:"success",report_status:"handoff_ready",attempts:1})},generation,newSocket);assert(ids["last-report-state"].textContent.includes("관리자 인계문 준비 완료")&&reportPollHandle===null,"automatic report status not rendered");
await onMessage({data:JSON.stringify({type:"tool.result",turn_id:1,tool:"start_step_timer",status:"error",code:"timer_not_configured"})},generation,newSocket);assert(newNode.querySelector(".tools").textContent.includes("현재 단계에 타이머 없음"),"tool error reason hidden");let ended;playContext={resume:async()=>{},createBuffer:()=>({getChannelData:()=>new Float32Array(1)}),createBufferSource:()=>({connect(){},start(){},set onended(fn){ended=fn},get onended(){return ended}}),destination:{}};activeTurn=1;queued.set(0,new ArrayBuffer(2));await pump(generation);assert(visibleState==="SPEAKING","playback not speaking");await onMessage({data:JSON.stringify({type:"audio.complete",turn_id:1})},generation,newSocket);await onMessage({data:JSON.stringify({type:"turn.done",turn_id:1,route:"brain",timings_ms:{stt:1,first_audio_ms:2,total_ms:3},segment_count:1,output_frames:1})},generation,newSocket);assert(newNode.querySelector(".stats").textContent.includes("경로 brain")&&newNode.querySelector(".stats").textContent.includes("첫 음성 2 ms"),"server route or first audio missing");assert(visibleState==="SPEAKING","done changed queued playback");ended();await Promise.resolve();assert(visibleState==="LISTENING","drained playback not listening");await onMessage({data:JSON.stringify({type:"turn.done",turn_id:1,route:"deterministic_emergency",timings_ms:{stt:1,total_ms:3},segment_count:0,output_frames:0})},generation,newSocket);assert(newNode.querySelector(".stats").textContent.includes("경로 deterministic_emergency")&&newNode.querySelector(".stats").textContent.includes("첫 음성 측정 안 됨")&&!newNode.querySelector(".stats").textContent.includes("undefined"),"missing first audio display unsafe");const lateEnded=ended;
await onMessage({data:JSON.stringify({type:"playback.completed",pipeline:"cascade",turn_id:1,playback_completion_ms:1234})},generation,newSocket);assert(newNode.querySelector(".stats").textContent.includes("재생 완료 1234 ms"),"playback completion metric missing");
sessionActive=true;let nativeStopped=false,nativeEnded=null;playContext={currentTime:0,resume:async()=>{},createBuffer:(_,length,rate)=>({duration:length/rate,getChannelData:()=>new Float32Array(length)}),createBufferSource:()=>({connect(){},start(){},stop(){nativeStopped=true},disconnect(){},set onended(fn){nativeEnded=fn},get onended(){return nativeEnded}}),destination:{}};
await onMessage({data:JSON.stringify({type:"native.response.created",turn_id:2,response_id:"native-1"})},generation,newSocket);await onMessage({data:JSON.stringify({type:"native.output.item",turn_id:2,response_id:"native-1",item_id:"item-1"})},generation,newSocket);
await onMessage({data:JSON.stringify({type:"native.audio.delta",turn_id:2,response_id:"native-1",item_id:"item-1",sample_rate:24000,byte_length:960})},generation,newSocket);await onMessage({data:new ArrayBuffer(960)},generation,newSocket);assert(nativeSources.size===1&&visibleState==="SPEAKING","native audio not scheduled");await onMessage({data:JSON.stringify({type:"native.response.done",turn_id:2,response_id:"native-1"})},generation,newSocket);assert(activeNativeResponseId==="native-1"&&nativeSources.size===1,"response.done incorrectly ended local playback");
playContext.currentTime=.02;await onMessage({data:JSON.stringify({type:"native.playback.clear",reason:"barge_in",turn_id:2,response_id:"native-1",item_id:"item-1"})},generation,newSocket);const truncate=JSON.parse(newSocket.sent.at(-1)),interruptedAssistant=turnNode(2,generation);assert(nativeStopped&&nativeSources.size===0,"barge-in did not stop playback");assert(truncate.type==="native.playback.truncate"&&truncate.response_id==="native-1"&&Number.isInteger(truncate.audio_end_ms)&&truncate.audio_end_ms===10,"unsafe native truncation metadata");assert(interruptedAssistant.querySelector(".reply").textContent==="사용자 개입으로 중단됨","interrupted assistant turn not labeled");
await onMessage({data:JSON.stringify({type:"speech.start",turn_id:3})},generation,newSocket);const followingTurn=turnNode(3,generation);assert(followingTurn.querySelector(".reply").textContent==="","new user turn was marked interrupted");await onMessage({data:JSON.stringify({type:"reply.delta",turn_id:2,text:"late old audio"})},generation,newSocket);await onMessage({data:JSON.stringify({type:"playback.completed",pipeline:"native",turn_id:2,playback_completion_ms:999})},generation,newSocket);assert(interruptedAssistant.querySelector(".reply").textContent==="사용자 개입으로 중단됨"&&!interruptedAssistant.querySelector(".stats").textContent.includes("재생 완료"),"late event overwrote interruption or completion state");await onMessage({data:JSON.stringify({type:"playback.completed",pipeline:"native",turn_id:3,playback_completion_ms:321})},generation,newSocket);assert(followingTurn.querySelector(".stats").textContent.includes("재생 완료 321 ms")&&interruptedAssistant.querySelector(".reply").textContent==="사용자 개입으로 중단됨","later turn overwrote interrupted turn");
await onMessage({data:JSON.stringify({type:"native.response.created",turn_id:3,response_id:"native-2"})},generation,newSocket);await onMessage({data:JSON.stringify({type:"native.output.item",turn_id:3,response_id:"native-2",item_id:"item-2"})},generation,newSocket);await onMessage({data:JSON.stringify({type:"native.audio.delta",turn_id:3,response_id:"native-2",item_id:"item-2",sample_rate:24000,byte_length:960})},generation,newSocket);await onMessage({data:new ArrayBuffer(960)},generation,newSocket);const sentBeforeToolClear=newSocket.sent.length;await onMessage({data:JSON.stringify({type:"native.playback.clear",reason:"tool_validation",turn_id:3,response_id:"native-2",item_id:"item-2"})},generation,newSocket);assert(nativeStopped&&newSocket.sent.length===sentBeforeToolClear&&visibleState==="THINKING","tool validation clear was not silent");await onMessage({data:JSON.stringify({type:"native.response.created",turn_id:3,response_id:"native-3"})},generation,newSocket);await onMessage({data:JSON.stringify({type:"native.output.item",turn_id:3,response_id:"native-3",item_id:"item-3"})},generation,newSocket);await onMessage({data:JSON.stringify({type:"native.audio.delta",turn_id:3,response_id:"native-3",item_id:"item-3",sample_rate:24000,byte_length:960})},generation,newSocket);await onMessage({data:new ArrayBuffer(960)},generation,newSocket);await onMessage({data:JSON.stringify({type:"native.response.done",turn_id:3,response_id:"native-3",awaiting_tool_continuation:true})},generation,newSocket);assert(JSON.parse(newSocket.sent.at(-1)).type!=="native.playback.ended","tool continuation started before playback drain");nativeEnded();const playbackEnded=JSON.parse(newSocket.sent.at(-1));assert(playbackEnded.type==="native.playback.ended"&&playbackEnded.response_id==="native-3"&&visibleState==="THINKING","playback completion handshake failed");
await stopSession();lateEnded();await Promise.resolve();assert(visibleState==="IDLE","late playback callback changed state");
await onMessage({data:JSON.stringify({type:"reply.delta",turn_id:1,text:"late"})},0,oldSocket);assert(newNode.querySelector(".reply").textContent===authoritativeDisplay+" ","stale text accepted");
for(const state of ["IDLE","CONNECTING","LISTENING","THINKING","SPEAKING","ERROR"]){renderState(state);await stopSession();assert(visibleState==="IDLE"&&!ids.start.disabled&&ids.stop.disabled,"stop from "+state);}
await onMessage({data:JSON.stringify({type:"state.changed",state:"AGENT_SPEAKING"})},generation,newSocket);assert(visibleState==="IDLE","old speaking event accepted");
socket=new WS();ids["pipeline-mode"].value="cascade";ids["manual-language"].value="ko";ids["protocol-id"].value="";await startSession();const unselectedRequest=JSON.parse(socket.sent.at(-1));await onMessage({data:JSON.stringify({type:"session.configuration_required",configuration_id:unselectedRequest.configuration_id,mode:"cascade",language:"ko",protocol_id:null,reason:"protocol_selection_required"})},sessionGeneration,socket);assert(!sessionActive&&acceptedSessionConfiguration===null&&visibleState==="IDLE"&&ids["session-configuration-status"].textContent.includes("정확한 프로토콜"),"mode-only request masqueraded as ready");await stopSession();
socket=null;const reconnectPromise=init(sessionGeneration),reconnectSocket=socket;reconnectSocket.onopen();await reconnectPromise;acceptedSessionConfiguration={configuration_id:999,mode:"cascade",language:"ko",protocol_id:"candidate-a-curated-development-v1"};sessionActive=true;renderCuratedProtocolState({configuration_id:999,state:{...curated0,revision:0}});renderState("LISTENING");reconnectSocket.onclose();await Promise.resolve();assert(!sessionActive&&acceptedSessionConfiguration===null&&visibleState==="ERROR"&&ids["session-configuration-status"].textContent.includes("다시 선택")&&curatedProtocolState.attached===false&&ids["procedure-title"].textContent.includes("없음"),"reconnect silently retained accepted configuration or curated state");await stopSession();
for(let i=0;i<3;i++){socket=new WS();ids["pipeline-mode"].value="cascade";ids["manual-language"].value="ko";ids["protocol-id"].value="candidate-a-curated-development-v1";await startSession();assert(visibleState==="CONNECTING","restart connecting");const request=JSON.parse(socket.sent.at(-1));await onMessage({data:JSON.stringify({type:"session.ready",configuration_id:request.configuration_id,mode:"cascade",language:"ko",protocol_id:"candidate-a-curated-development-v1",revision_id:"fixture-test"})},sessionGeneration,socket);assert(visibleState==="LISTENING"&&ids.start.disabled&&!ids.stop.disabled&&ids.status.textContent==="듣고 있습니다…","restart active controls");await stopSession();assert(visibleState==="IDLE"&&!ids.start.disabled&&ids.stop.disabled&&ids.status.textContent==="준비됨 · 세션 시작을 한 번 눌러주세요.","restart idle controls");}
})().catch(e=>{console.error(e);process.exit(1)});
"""
        result = subprocess.run(["node", "-e", harness], cwd=ROOT, text=True, capture_output=True)
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_cascade_generation_clear_and_provisional_turn_cleanup(self):
        html=(
            ROOT/"src"/"voice_workflow_agent"/"static"/"index.html"
        ).read_text(encoding="utf-8")
        script=html.split("<script>",1)[1].split("</script>",1)[0]
        harness=r"""
const assert=(ok,message)=>{if(!ok)throw new Error(message)};
class Element{constructor(){this.children=[];this.fields={};this.textContent="";this.disabled=false;this.hidden=false;this.removed=false;this.dataset={};this.options=[]}set innerHTML(v){for(const c of ["transcript","reply","turn-status","filler-status","tools","turn-visual","stats","error"]){const item=new Element();item.textContent=c==="transcript"?"듣는 중…":"";this.fields[c]=item}}querySelector(s){return this.fields[s.slice(1)]}prepend(n){this.children.unshift(n)}replaceChildren(){this.children=[];this.options=this.children}appendChild(n){this.children.push(n);this.options=this.children}remove(){this.removed=true}addEventListener(){}setAttribute(){}}
const ids=Object.fromEntries(["start","stop","log","status","state","last-report-id","last-report-state","pending-report","language-status","language-mode","manual-language","pipeline-mode","protocol-id","protocol-pdf","register-protocol","protocol-upload-status","protocol-readiness","protocol-revision","session-configuration-status","new-user","language-confirmation","procedure-title","procedure-meta","procedure-status","procedure-progress","procedure-step-title","procedure-instruction","procedure-warning","procedure-spoken-summary","repeat-step","next-step","voice-command-hint","procedure-visual","source-visual-state","source-filename","source-page-number","source-short-hash","voice-processing","voice-filler-status","voice-primary-status","procedure-source","procedure-timer","procedure-observation","procedure-handoff","procedure-audit"].map(x=>[x,new Element()]));
ids["language-mode"].value="manual";ids["manual-language"].value="ko";ids["pipeline-mode"].value="cascade";ids["protocol-id"].value="candidate-a-curated-development-v1";
globalThis.document={getElementById:id=>ids[id],createElement:()=>new Element()};globalThis.location={protocol:"http:",host:"test"};
class WS{static OPEN=1;static CLOSING=2;constructor(){this.readyState=1;this.sent=[]}send(value){this.sent.push(value)}close(){this.readyState=3}}
globalThis.WebSocket=WS;Object.defineProperty(globalThis,"navigator",{value:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[]})}},configurable:true});globalThis.AudioContext=class{};
"""+script+r"""
(async()=>{
 const current=socket,browserGeneration=sessionGeneration;
 acceptedSessionConfiguration={configuration_id:41,mode:"cascade",language:"ko",protocol_id:"candidate-a-curated-development-v1"};sessionActive=true;pipelineMode="cascade";
 let stoppedFirst=0,stoppedSecond=0,created=0;
 const firstSource={onended:()=>{},stop(){stoppedFirst++},disconnect(){}};
 const secondSource={onended:()=>{},stop(){stoppedSecond++},disconnect(){}};
 playContext={state:"running",resume:async()=>{},close:async()=>{},destination:{},createBuffer:()=>({getChannelData:()=>new Float32Array(1)}),createBufferSource:()=>{created++;return{onended:null,connect(){},start(){},stop(){},disconnect(){}}}};
 micWorkletNode={port:{onmessage:()=>{},postMessage(){}},disconnect(){}};const microphone=micWorkletNode;
 await onMessage({data:JSON.stringify({type:"speech.start",turn_id:1,generation:10})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"transcript",turn_id:1,generation:10,text:"현재 단계 전체를 읽어줘"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"reply.delta",turn_id:1,generation:10,text:"Canonical display text"})},browserGeneration,current);
 activeSource=firstSource;playing=true;queued.set(0,new ArrayBuffer(2));receiving={turn_id:1,generation:10,segment_index:1};receivedFrames=[new ArrayBuffer(2)];
 await onMessage({data:JSON.stringify({type:"cascade.playback.clear",configuration_id:41,turn_id:1,generation:9,revision:1,state:"cancelled",superseding_turn_id:2,superseding_generation:11,reason:"accepted_speech_onset"})},browserGeneration,current);
 assert(stoppedFirst===0&&activeTurn===1&&queued.size===1,"stale clear changed active audio");
 const clear={type:"cascade.playback.clear",configuration_id:41,turn_id:1,generation:10,revision:1,state:"cancelled",superseding_turn_id:2,superseding_generation:11,reason:"accepted_speech_onset"};
 await onMessage({data:JSON.stringify(clear)},browserGeneration,current);
 const interrupted=turnNode(1,browserGeneration);
 assert(stoppedFirst===1&&queued.size===0&&receiving===null&&activeTurn===null&&activeCascadeGeneration===null,"accepted clear did not stop exact Cascade playback");
 assert(interrupted.querySelector(".transcript").textContent==="현재 단계 전체를 읽어줘"&&interrupted.querySelector(".reply").textContent==="Canonical display text "&&interrupted.querySelector(".error").textContent==="중단됨","interrupted terminal card lost accepted content");
 assert(micWorkletNode===microphone&&sessionActive,"barge-in stopped microphone or session");
 await pump(browserGeneration);assert(created===0,"pump rescheduled stale queued audio");
 await onMessage({data:JSON.stringify(clear)},browserGeneration,current);assert(stoppedFirst===1,"duplicate clear was not idempotent");
 await onMessage({data:JSON.stringify({type:"reply.delta",turn_id:1,generation:10,text:"late"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"audio.segment.start",turn_id:1,generation:10,segment_index:2,frame_count:1})},browserGeneration,current);
 await onMessage({data:new ArrayBuffer(2)},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"audio.complete",turn_id:1,generation:10})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.done",turn_id:1,generation:10,route:"curated_protocol",timings_ms:{},segment_count:1})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"playback.completed",turn_id:1,generation:10,playback_completion_ms:99})},browserGeneration,current);
 assert(interrupted.querySelector(".reply").textContent==="Canonical display text "&&interrupted.querySelector(".stats").textContent===""&&interrupted.querySelector(".error").textContent==="중단됨"&&queued.size===0,"late stale event revived interrupted turn");
 await onMessage({data:JSON.stringify({type:"speech.start",turn_id:2,generation:11})},browserGeneration,current);activeSource=secondSource;playing=true;queued.set(0,new ArrayBuffer(2));
 await onMessage({data:JSON.stringify(clear)},browserGeneration,current);assert(activeTurn===2&&activeCascadeGeneration===11&&stoppedSecond===0&&queued.size===1,"stale clear removed newer generation");
 await onMessage({data:JSON.stringify({type:"transcript",turn_id:2,generation:11,text:"현재 단계 알려줘"})},browserGeneration,current);assert(turnNode(2,browserGeneration).querySelector(".transcript").textContent==="현재 단계 알려줘","superseding utterance was not accepted");
 clearPlayback();
 await onMessage({data:JSON.stringify({type:"speech.start",turn_id:3,generation:12})},browserGeneration,current);const rejected=turnNode(3,browserGeneration);await onMessage({data:JSON.stringify({type:"speech.rejected",turn_id:3,generation:12,reason:"minimum_voiced_frames"})},browserGeneration,current);assert(rejected.removed&&!turns.has(`${browserGeneration}:3`),"explicit no-speech did not remove provisional card");
 await onMessage({data:JSON.stringify({type:"speech.start",turn_id:4,generation:13})},browserGeneration,current);const activeCard=turnNode(4,browserGeneration);await onMessage({data:JSON.stringify({type:"speech.rejected",turn_id:3,generation:12,reason:"minimum_voiced_frames"})},browserGeneration,current);assert(turns.has(`${browserGeneration}:4`)&&!activeCard.removed,"stale rejection removed active listening card");
 await onMessage({data:JSON.stringify({type:"transcript",turn_id:4,generation:13,text:"accepted"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"speech.start",turn_id:5,generation:14})},browserGeneration,current);const stoppedCard=turnNode(5,browserGeneration);await onMessage({data:JSON.stringify({type:"session.stopped"})},browserGeneration,current);assert(stoppedCard.removed&&!turns.has(`${browserGeneration}:5`),"explicit session stop did not remove provisional card");
 sessionActive=true;await onMessage({data:JSON.stringify({type:"speech.start",turn_id:6,generation:15})},browserGeneration,current);const disconnected=turnNode(6,browserGeneration);current.onclose();await Promise.resolve();assert(disconnected.removed&&!turns.has(`${browserGeneration}:6`)&&turns.has(`${browserGeneration}:4`),"disconnect did not remove only provisional card");
 assert(!activeCard.removed&&activeCard.querySelector(".transcript").textContent==="accepted","disconnect removed accepted transcript card");
})().catch(error=>{console.error(error);process.exit(1)});
"""
        result=subprocess.run(
            ["node","-e",harness],cwd=ROOT,text=True,capture_output=True)
        self.assertEqual(result.returncode,0,result.stderr)

    def test_turn_card_applies_server_revisions_monotonically(self):
        html=(
            ROOT/"src"/"voice_workflow_agent"/"static"/"index.html"
        ).read_text(encoding="utf-8")
        script=html.split("<script>",1)[1].split("</script>",1)[0]
        harness=r"""
const assert=(ok,message)=>{if(!ok)throw new Error(message)};
class Element{constructor(){this.children=[];this.fields={};this.textContent="";this.disabled=false;this.hidden=false;this.removed=false;this.dataset={};this.options=[]}set innerHTML(v){for(const c of ["transcript","reply","turn-status","filler-status","tools","turn-visual","stats","error"]){const item=new Element();item.textContent=c==="transcript"?"듣는 중…":"";this.fields[c]=item}}querySelector(s){return this.fields[s.slice(1)]}prepend(n){this.children.unshift(n)}replaceChildren(){this.children=[];this.options=this.children}appendChild(n){this.children.push(n);this.options=this.children}remove(){this.removed=true}addEventListener(){}setAttribute(){}}
const ids=Object.fromEntries(["start","stop","log","status","state","last-report-id","last-report-state","pending-report","language-status","language-mode","manual-language","pipeline-mode","protocol-id","protocol-pdf","register-protocol","protocol-upload-status","protocol-readiness","protocol-revision","session-configuration-status","new-user","language-confirmation","procedure-title","procedure-meta","procedure-status","procedure-progress","procedure-step-title","procedure-instruction","procedure-warning","procedure-spoken-summary","repeat-step","next-step","voice-command-hint","procedure-visual","source-visual-state","source-filename","source-page-number","source-short-hash","voice-processing","voice-filler-status","voice-primary-status","procedure-source","procedure-timer","procedure-observation","procedure-handoff","procedure-audit"].map(x=>[x,new Element()]));
ids["language-mode"].value="manual";ids["manual-language"].value="ko";ids["pipeline-mode"].value="cascade";ids["protocol-id"].value="candidate-a-curated-development-v1";
globalThis.document={getElementById:id=>ids[id],createElement:()=>new Element()};globalThis.location={protocol:"http:",host:"test"};
class WS{static OPEN=1;static CLOSING=2;constructor(){this.readyState=1;this.sent=[]}send(value){this.sent.push(value)}close(){this.readyState=3}}
globalThis.WebSocket=WS;Object.defineProperty(globalThis,"navigator",{value:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[]})}},configurable:true});globalThis.AudioContext=class{};
"""+script+r"""
(async()=>{
 const current=socket,browserGeneration=sessionGeneration,configuration_id=51,base={configuration_id,turn_id:1,generation:10};
 acceptedSessionConfiguration={configuration_id,mode:"cascade",language:"ko",protocol_id:"candidate-a-curated-development-v1"};sessionActive=true;pipelineMode="cascade";
 await onMessage({data:JSON.stringify({type:"speech.start",turn_id:1,generation:10})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:1,state:"listening"})},browserGeneration,current);
 const node=turnNode(1,browserGeneration);assert(node.querySelector(".turn-status").textContent==="듣는 중…","listening state missing");
 await onMessage({data:JSON.stringify({type:"transcript",turn_id:1,generation:10,text:"현재 단계 알려줘"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"reply.delta",turn_id:1,generation:10,text:"Canonical display",speech_text:"Short speech"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:3,state:"transcribing"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:2,state:"routing"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:3,state:"routing"})},browserGeneration,current);
 assert(node.querySelector(".turn-status").textContent==="음성 인식 중…","lower or duplicate revision regressed state");
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:4,state:"routing"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:5,state:"checking_protocol",route:"curated_protocol"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:6,state:"synthesizing",route:"curated_protocol"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:7,state:"playing",route:"curated_protocol",timings_ms:{time_to_playable_audio:12}})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:8,state:"complete",route:"curated_protocol",timings_ms:{playback_completion:20}})},browserGeneration,current);
 assert(node.querySelector(".turn-status").textContent==="완료 · 개발용 절차","complete state missing");
 assert(node.querySelector(".transcript").textContent==="현재 단계 알려줘"&&node.querySelector(".reply").textContent==="Canonical display "&&!node.querySelector(".reply").textContent.includes("Short speech"),"progress lost transcript/display separation");
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:9,state:"playing",route:"curated_protocol"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,configuration_id:99,revision:20,state:"error"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,generation:9,revision:20,state:"error"})},browserGeneration,current);
 assert(node.querySelector(".turn-status").textContent==="완료 · 개발용 절차"&&!node.querySelector(".error").textContent,"terminal or stale identity revived card");
 const visible=node.querySelector(".turn-status").textContent+node.querySelector(".error").textContent;for(const forbidden of ["prompt","reasoning","tool arguments","Traceback"])assert(!visible.includes(forbidden),"hidden internals exposed");
})().catch(error=>{console.error(error);process.exit(1)});
"""
        result=subprocess.run(
            ["node","-e",harness],cwd=ROOT,text=True,capture_output=True)
        self.assertEqual(result.returncode,0,result.stderr)

    def test_audio_worklet_accumulates_twenty_ms_transferable_blocks(self):
        worklet=(
            ROOT/"src"/"voice_workflow_agent"/"static"/"mic-capture-worklet.js"
        ).read_text(encoding="utf-8")
        harness=r"""
const assert=(ok,message)=>{if(!ok)throw new Error(message)};
let Processor=null,posted=[];
globalThis.sampleRate=48000;
globalThis.AudioWorkletProcessor=class{constructor(){this.port={onmessage:null,postMessage:(value,transfer)=>posted.push({value,transfer})}}};
globalThis.registerProcessor=(name,value)=>{assert(name==="voice-workflow-mic-capture","processor name");Processor=value};
""" + worklet + r"""
const processor=new Processor(),block=new Float32Array(128);block.fill(.25);
for(let i=0;i<8;i++)assert(processor.process([ [block] ]),"processor stopped early");
assert(posted.length===1,"128-sample blocks were not accumulated");
assert(posted[0].value instanceof ArrayBuffer&&posted[0].value.byteLength===960*4,"batch is not 20 ms Float32");
assert(posted[0].transfer.length===1&&posted[0].transfer[0]===posted[0].value,"batch was not transferred");
processor.port.onmessage({data:{type:"stop"}});
assert(processor.process([ [block] ])===false,"stopped processor remained active");
"""
        result=subprocess.run(
            ["node","-e",harness],cwd=ROOT,text=True,capture_output=True)
        self.assertEqual(result.returncode,0,result.stderr)

    def test_protocol_visual_and_filler_use_production_handlers(self):
        html=(
            ROOT/"src"/"voice_workflow_agent"/"static"/"index.html"
        ).read_text(encoding="utf-8")
        script=html.split("<script>",1)[1].split("</script>",1)[0]
        harness=r"""
const assert=(ok,message)=>{if(!ok)throw new Error(message)};
class Element{constructor(){this.children=[];this.fields={};this.textContent="";this.disabled=false;this.hidden=false;this.removed=false;this.dataset={};this.options=[];this.attributes={}}set innerHTML(v){for(const c of ["transcript","reply","turn-status","filler-status","tools","turn-visual","stats","error"]){const item=new Element();item.textContent=c==="transcript"?"듣는 중…":"";this.fields[c]=item}}querySelector(s){return this.fields[s.slice(1)]}prepend(n){this.children.unshift(n)}replaceChildren(){this.children=[];this.options=this.children}appendChild(n){this.children.push(n);this.options=this.children}remove(){this.removed=true}addEventListener(kind,fn){this["on"+kind]=fn}setAttribute(name,value){this.attributes[name]=value}}
const names=["start","stop","log","status","state","last-report-id","last-report-state","pending-report","language-status","language-mode","manual-language","pipeline-mode","protocol-id","protocol-pdf","register-protocol","protocol-upload-status","protocol-readiness","protocol-revision","session-configuration-status","new-user","language-confirmation","procedure-title","procedure-meta","procedure-status","procedure-progress","procedure-step-title","procedure-instruction","procedure-warning","procedure-spoken-summary","repeat-step","next-step","voice-command-hint","procedure-visual","source-visual-state","source-filename","source-page-number","source-short-hash","voice-processing","voice-filler-status","voice-primary-status","procedure-source","procedure-timer","procedure-observation","procedure-handoff","procedure-audit"];
const ids=Object.fromEntries(names.map(x=>{const element=new Element();element.id=x;return[x,element]}));ids["language-mode"].value="manual";ids["manual-language"].value="ko";ids["pipeline-mode"].value="cascade";ids["protocol-id"].value="protocol-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";for(const stage of ["recognized","routed","protocol","prepared","audio"]){const item=new Element();item.dataset.stage=stage;ids["voice-processing"].appendChild(item);}
globalThis.document={getElementById:id=>ids[id],createElement:()=>new Element(),querySelector:()=>null};globalThis.location={protocol:"http:",host:"test"};globalThis.addEventListener=()=>{};
class WS{static OPEN=1;static CLOSING=2;constructor(){this.readyState=1;this.sent=[]}send(v){this.sent.push(v)}close(){this.readyState=3}}
globalThis.WebSocket=WS;Object.defineProperty(globalThis,"navigator",{value:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[]})}},configurable:true});globalThis.AudioContext=class{};
"""+script+r"""
(async()=>{const current=socket,browserGeneration=sessionGeneration,protocol_id="protocol-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",revision_id="pdf-1-analysis-1",configuration_id=71;acceptedSessionConfiguration={configuration_id,mode:"cascade",language:"ko",protocol_id,revision_id};sessionActive=true;pipelineMode="cascade";
let fillerStopped=0;playContext={state:"running",destination:{},resume:async()=>{},createBuffer:()=>({getChannelData:()=>new Float32Array(320)}),createBufferSource:()=>({onended:null,connect(){},start(){},stop(){fillerStopped++},disconnect(){}})};
await onMessage({data:JSON.stringify({type:"speech.start",turn_id:1,generation:5})},browserGeneration,current);
const visual={asset_id:"source-page-1",protocol_id,revision_id,kind:"full_source_page_preview",source_document_id:"b".repeat(64),source_page:1,mime_type:"application/pdf",sha256:"b".repeat(64),alt_text:"Source PDF page 1 preview",normalized_bounding_box:null,url:`/api/protocols/${protocol_id}/revisions/${revision_id}/assets/source-page-1`};
const state={attached:true,protocol_id,revision_id,display_name:"Protocol Alpha",development_only:false,readiness_status:"guidance_ready",active:true,current_step_label:"1",current_step_id:"step-1",total_steps:1,at_final_step:true,block_reason:null,revision:1,display_summary:"1. Add solution.",spoken_summary:"Step one is ready.",source_filename:"alpha.pdf",source_sha256:"b".repeat(64),source_page_refs:[1],visual_assets:[visual],visual_status:"available",warning_texts:["Keep safe."],critical_warning_texts:[]};
await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id,turn_id:1,generation:5,state,action:"current"})},browserGeneration,current);assert(ids["procedure-instruction"].textContent==="1. Add solution."&&ids["procedure-warning"].textContent.includes("Keep safe.")&&!ids["procedure-warning"].hidden,"warning not independently readable");assert(ids["procedure-spoken-summary"].textContent==="Step one is ready."&&ids["source-filename"].textContent==="alpha.pdf"&&ids["source-page-number"].textContent==="p.1"&&ids["source-short-hash"].textContent.startsWith("bbbbbbbbbbbb"),"source or speech metadata missing");assert(ids["procedure-visual"].children.length===3&&ids["procedure-visual"].children[1].src.includes("#page=1")&&ids["source-visual-state"].textContent.includes("불러오는 중"),"current visual loading state missing");ids["procedure-visual"].children[1].onload();assert(ids["source-visual-state"].textContent==="검증된 원문 페이지","current visual ready state missing");const turnVisual=turnNode(1,browserGeneration).querySelector(".turn-visual");assert(turnVisual.children.length===3,"turn visual missing");
const stale={...state,revision:0,current_step_label:"9",visual_assets:[]};await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id,turn_id:1,generation:5,state:stale,action:"next"})},browserGeneration,current);assert(curatedProtocolState.current_step_label==="1"&&turnVisual.children.length===3,"stale visual replaced current state");
const wrongAsset={...visual,protocol_id:"protocol-cccccccccccccccccccccccccccccccc"},wrongState={...state,revision:2,visual_assets:[wrongAsset]};await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id,turn_id:2,generation:6,state:wrongState,action:"current"})},browserGeneration,current);assert(ids["procedure-visual"].children.length===1,`mismatched visual was trusted: ${ids["procedure-visual"].children.length}`);assert(ids["source-visual-state"].textContent.includes("검증 실패"),`visual failure state missing: ${ids["source-visual-state"].textContent}`);assert(ids["procedure-instruction"].textContent==="1. Add solution.",`instruction fallback disappeared: ${ids["procedure-instruction"].textContent}`);assert(ids["procedure-warning"].textContent.includes("Keep safe."),`warning fallback disappeared: ${ids["procedure-warning"].textContent}`);assert(turnVisual.children.length===3,"historical visual changed with current state");
const wrongHashAsset={...visual,sha256:"c".repeat(64),source_document_id:"c".repeat(64)},wrongHashState={...state,revision:3,visual_assets:[wrongHashAsset]};await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id,turn_id:3,generation:7,state:wrongHashState,action:"current"})},browserGeneration,current);assert(ids["procedure-visual"].children.length===1&&ids["source-visual-state"].textContent.includes("검증 실패"),"visual with wrong source identity was trusted");
const unavailableState={...state,revision:4,visual_assets:[],visual_status:"unavailable"};await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id,turn_id:4,generation:8,state:unavailableState,action:"current"})},browserGeneration,current);assert(ids["source-visual-state"].textContent.includes("사용 가능한 시각 자료 없음")&&ids["procedure-instruction"].textContent==="1. Add solution.","text-only visual fallback missing");const failedLoadState={...state,revision:5};await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id,turn_id:5,generation:9,state:failedLoadState,action:"current"})},browserGeneration,current);ids["procedure-visual"].children[1].onerror();assert(ids["source-visual-state"].textContent.includes("미리보기 불러오기 실패")&&ids["procedure-instruction"].textContent==="1. Add solution.","visual load failure removed instruction");assert(turnVisual.children.length===3,"historical visual changed after fallback states");
const turnState={type:"turn.state",configuration_id,turn_id:1,generation:5};await onMessage({data:JSON.stringify({...turnState,revision:1,state:"routing",route:"curated_protocol"})},browserGeneration,current);await onMessage({data:JSON.stringify({...turnState,revision:2,state:"checking_protocol",route:"curated_protocol"})},browserGeneration,current);await onMessage({data:JSON.stringify({...turnState,revision:3,state:"synthesizing",route:"curated_protocol"})},browserGeneration,current);await onMessage({data:JSON.stringify({...turnState,revision:4,state:"playing",route:"curated_protocol"})},browserGeneration,current);assert(ids["voice-processing"].children[4].className==="active"&&ids["voice-primary-status"].textContent.includes("재생 중"),"primary playing state missing");
await onMessage({data:JSON.stringify({type:"filler.audio.start",configuration_id,turn_id:1,generation:5,frame_count:1,sample_rate:16000,encoding:"pcm_s16le"})},browserGeneration,current);await onMessage({data:new ArrayBuffer(640)},browserGeneration,current);await onMessage({data:JSON.stringify({type:"filler.audio.end",configuration_id,turn_id:1,generation:5,frame_count:1})},browserGeneration,current);assert(fillerSource!==null,"eligible filler did not enter the playback scheduler");await onMessage({data:JSON.stringify({type:"audio.segment.start",turn_id:1,generation:5,segment_index:0,frame_count:1})},browserGeneration,current);assert(fillerStopped===1&&fillerSource===null&&receiving.segment_index===0,"primary did not atomically stop filler");
await onMessage({data:JSON.stringify({type:"turn.filler",configuration_id,turn_id:1,generation:5,outcome:"scheduled"})},browserGeneration,current);assert(ids["voice-filler-status"].textContent.includes("대기"),"filler scheduled state missing");await onMessage({data:JSON.stringify({type:"turn.filler",configuration_id,turn_id:1,generation:5,outcome:"played"})},browserGeneration,current);assert(turnNode(1,browserGeneration).querySelector(".filler-status").textContent.includes("대기 안내")&&ids["voice-filler-status"].textContent==="재생됨","filler played status missing");await onMessage({data:JSON.stringify({type:"turn.filler",configuration_id,turn_id:1,generation:5,outcome:"skipped"})},browserGeneration,current);assert(ids["voice-filler-status"].textContent.includes("생략"),"filler skipped state missing");await onMessage({data:JSON.stringify({type:"turn.filler",configuration_id,turn_id:1,generation:5,outcome:"cancelled"})},browserGeneration,current);assert(ids["voice-filler-status"].textContent==="취소됨","filler cancelled state missing");
const catalogEntries=[
 {protocol_id:"protocol-1",title:"Ready",revision_id:"pdf-1-analysis-1",readiness_status:"guidance_ready",analysis_status:"validated",available_for_execution:true},
 {protocol_id:"protocol-2",title:"Review",revision_id:"pdf-1",readiness_status:"analysis_required",analysis_status:"structured_analysis_ready",available_for_execution:false},
 {protocol_id:"protocol-3",title:"OCR",revision_id:"pdf-1",readiness_status:"analysis_required",analysis_status:"ocr_required",available_for_execution:false},
 {protocol_id:"protocol-4",title:"Failed",revision_id:"pdf-1",readiness_status:"analysis_required",analysis_status:"analysis_failed",available_for_execution:false},
 {protocol_id:"protocol-5",title:"Large",revision_id:"pdf-1",readiness_status:"analysis_required",analysis_status:"chunked_analysis_required",available_for_execution:false}
];
fetch=async()=>{assert(ids["protocol-readiness"].textContent.includes("불러오는 중"),"catalog loading state missing");return{ok:true,json:async()=>({protocols:catalogEntries})}};ids["protocol-id"].value="unavailable-old-selection";await loadProtocolCatalog();assert(protocolCatalog.size===5,`catalog size: ${protocolCatalog.size}`);assert(ids["protocol-id"].value==="protocol-1",`ready selection missing: ${ids["protocol-id"].value}; options=${ids["protocol-id"].options.map(option=>`${option.value}/${option.disabled}`).join(",")}`);assert(ids["protocol-readiness"].textContent.includes("실행 준비"),`ready status missing: ${ids["protocol-readiness"].textContent}`);for(const [id,label] of [["protocol-2","구조화 분석"],["protocol-3","OCR 필요"],["protocol-4","분석 실패"],["protocol-5","대형 문서 분석 연기"]]){ids["protocol-id"].value=id;renderSelectedProtocolContext();assert(ids["protocol-readiness"].textContent.includes(label),`catalog state missing: ${id}`);}renderState("LISTENING");assert(ids["protocol-id"].disabled&&ids["protocol-id"].attributes["aria-disabled"]==="true","active session did not accessibly lock selector");fetch=async()=>({ok:false,json:async()=>({})});await loadProtocolCatalog();assert(ids["protocol-readiness"].textContent.includes("불러오기 실패")&&ids["protocol-id"].children.length===1,"catalog failure state missing");
})().catch(error=>{console.error(error);process.exit(1)});
"""
        result=subprocess.run(
            ["node","-e",harness],cwd=ROOT,text=True,capture_output=True)
        self.assertEqual(result.returncode,0,result.stderr)

    def test_protocol_workspace_is_responsive_and_accessible(self):
        html=(
            ROOT/"src"/"voice_workflow_agent"/"static"/"index.html"
        ).read_text(encoding="utf-8")
        self.assertIn('grid-template-areas:"step visual processing"', html)
        self.assertIn('grid-template-areas:"step" "visual" "processing"', html)
        self.assertLess(
            html.index('class="panel timeline"'),
            html.index('class="example-strip"'),
        )
        self.assertIn('button:focus-visible', html)
        self.assertIn('aria-describedby="protocol-readiness protocol-revision"', html)
        self.assertIn('role="alert" hidden', html)
        self.assertNotIn("overflow-x:scroll", html)

    def test_audio_worklet_module_is_in_the_fastapi_static_mount(self):
        from voice_workflow_agent.server import app

        static_mount=next(
            route for route in app.routes
            if getattr(route,"name",None)=="static")
        path,stat_result=static_mount.app.lookup_path(
            "mic-capture-worklet.js")
        self.assertTrue(Path(path).is_file())
        self.assertIsNotNone(stat_result)

if __name__ == "__main__": unittest.main()
