import subprocess, unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def run_node_harness(harness: str):
    """Feed large production-script harnesses over stdin, not argv."""
    return subprocess.run(
        ["node", "-"], cwd=ROOT, text=True, input=harness,
        capture_output=True,
    )

class FrontendSessionTests(unittest.TestCase):
    def test_chat_viewport_and_late_visual_use_production_handlers(self):
        html = (
            ROOT / "src" / "voice_workflow_agent" / "static" / "index.html"
        ).read_text(encoding="utf-8")
        self.assertIn("align-items:start", html)
        self.assertIn("position:sticky", html)
        self.assertIn("top:4.5rem", html)
        self.assertIn("calc(100vh - 5.5rem)", html)
        self.assertIn("min-height:24rem", html)
        self.assertIn("overflow-y:auto", html)
        self.assertIn('role="log"', html)
        script = html.split("<script>", 1)[1].split("</script>", 1)[0]
        harness = r"""
const assert=(ok,message)=>{if(!ok)throw new Error(message)};
class Element{constructor(){this.children=[];this.fields={};this.textContent="";this.hidden=false;this.disabled=false;this.dataset={};this.options=[];this.scrollTop=0;this.scrollHeight=0;this.clientHeight=300;this.offsetTop=0;this.attributes={}}get firstChild(){return this.children[0]||null}insertBefore(n,ref){const i=this.children.indexOf(ref);if(i>=0)this.children.splice(i,0,n);else this.children.unshift(n);this.options=this.children;this.scrollHeight=this.children.length*100;return n}set innerHTML(v){for(const c of ["transcript","reply","turn-status","filler-status","server-operation","tools","replay-status","turn-visual","stats","error"]){const item=new Element();item.textContent=c==="transcript"?"듣는 중…":"";this.fields[c]=item}}querySelector(s){if(s.startsWith("."))return this.fields[s.slice(1)]||this.children.find(item=>String(item.className||"").split(" ").includes(s.slice(1)))||null;return null}replaceChildren(...items){this.children=[...items];this.options=this.children;this.scrollHeight=this.children.length*100}appendChild(n){n.offsetTop=this.children.length*100;this.children.push(n);this.options=this.children;this.scrollHeight=this.children.length*100;return n}prepend(n){this.children.unshift(n)}remove(){this.removed=true}setAttribute(name,value){this.attributes[name]=value}addEventListener(kind,fn){this["on"+kind]=fn}}
const names=["start","stop","log","new-chat-update","status","state","last-report-id","last-report-state","pending-report","language-status","pipeline-mode","protocol-id","protocol-pdf","register-protocol","protocol-upload-status","protocol-analysis-progress","protocol-readiness","protocol-revision","session-configuration-status","new-user","language-confirmation","procedure-title","procedure-meta","procedure-status","procedure-progress","procedure-step-title","procedure-primary","procedure-instruction","procedure-warning","procedure-spoken-summary","repeat-step","next-step","voice-command-hint","procedure-visual","source-visual-state","source-filename","source-page-number","source-short-hash","voice-processing","voice-filler-status","voice-primary-status","procedure-source","procedure-timer","procedure-observation","procedure-handoff","procedure-audit"];
const ids=Object.fromEntries(names.map(name=>[name,new Element()]));ids["pipeline-mode"].value="cascade";ids["protocol-id"].value="candidate-a";
globalThis.document={getElementById:id=>ids[id],createElement:()=>new Element(),querySelector:()=>null};globalThis.location={protocol:"http:",host:"test"};globalThis.addEventListener=()=>{};
class WS{static OPEN=1;constructor(){this.readyState=1;this.sent=[]}send(v){this.sent.push(v)}}globalThis.WebSocket=WS;Object.defineProperty(globalThis,"navigator",{value:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[]})}},configurable:true});globalThis.AudioContext=class{};
""" + script + r"""
(async()=>{const current=socket,browserGeneration=sessionGeneration,configuration_id=7,protocol_id="candidate-a",revision_id="fixture-1",source="a".repeat(64);acceptedSessionConfiguration={configuration_id,mode:"cascade",language:"ko",protocol_id,revision_id};curatedProtocolState={attached:true,protocol_id,revision_id,source_sha256:source};sessionActive=true;pipelineMode="cascade";
ids.log.scrollHeight=300;ids.log.scrollTop=0;ids.log.clientHeight=300;const first=turnNode(1,browserGeneration),second=turnNode(2,browserGeneration);assert(ids.log.children[0]===second&&ids.log.children[1]===first,"turns are not newest-to-oldest");
ids.log.scrollHeight=1000;ids.log.scrollTop=100;ids.log.clientHeight=300;turnNode(3,browserGeneration);
await onMessage({data:JSON.stringify({type:"speech.start",turn_id:4,generation:9})},browserGeneration,current);const base={configuration_id,turn_id:4,generation:9,protocol_id,step_id:"step-2",source_document_hash:source,visual_job_id:"b".repeat(64)};await onMessage({data:JSON.stringify({type:"protocol.visual.state",...base,status:"visual_pending",visual_requested_ms:12})},browserGeneration,current);const card=turnNode(4,browserGeneration),visual=card.querySelector(".turn-visual");assert(visual.textContent!==""||visual.children.length>0,"visual pending did not patch the originating turn");const asset={asset_id:"c".repeat(64),kind:"generated_instructional",protocol_id,revision_id,step_id:"step-2",step_label:"2",source_document_id:source,source_page:2,source_evidence_ids:["current_step"],mime_type:"image/png",sha256:"c".repeat(64),width:1024,height:768,url:`/api/generated-visuals/${"c".repeat(64)}`,label:"AI-generated instructional illustration · not an original source image",caption_primary:"2단계 설명용 생성 이미지",caption_source:"Exact amounts remain controlled by text."};await onMessage({data:JSON.stringify({type:"protocol.visual.state",...base,status:"visual_ready",visual_ready_ms:55,asset})},browserGeneration,current);assert(ids.log.children.filter(item=>item===card).length===1&&visual.children.some(item=>item.src===asset.url),"late visual created a new turn or was not same-origin rendered");const count=visual.children.length;await onMessage({data:JSON.stringify({type:"protocol.visual.state",...base,status:"visual_ready",visual_ready_ms:99,asset})},browserGeneration,current);assert(visual.children.length===count,"duplicate visual event duplicated UI");
const citations=[{document_title:"Approved fictional guide",document_version:"1",section:"handling",page_number:2,chunk_id:"d".repeat(64)}];renderStructuredReply(card,{text:"ignored",primary_text:"추가 참고 안내",source_texts:["Original reference excerpt."],source_pages:[2],evidence_ids:["d".repeat(64)],answer_origin:"approved_lab_corpus",citations});assert(card.querySelector(".reply").children.some(item=>item.className==="reference-details"),"reference citation details are inaccessible");
const external=[{title:"Authoritative record",canonical_url:"https://pubchem.ncbi.nlm.nih.gov/compound/962",domain:"pubchem.ncbi.nlm.nih.gov"}];renderStructuredReply(card,{text:"ignored",primary_text:"AMBIC is ammonium bicarbonate [[1]](https://pubchem.ncbi.nlm.nih.gov/compound/962)</eos>",source_texts:[],source_pages:[],evidence_ids:[],answer_origin:"external_authoritative_reference",citations:external});const externalDetails=card.querySelector(".reply").querySelector(".reference-details"),externalLinks=externalDetails.children[1].children.at(-1),externalLink=externalLinks.children[0];assert(externalLink.href===external[0].canonical_url&&externalLink.target==="_blank"&&externalLink.rel==="noopener noreferrer","validated external citation was not rendered as a safe clickable link");assert(sanitizeExternalResearchAnswer("AMBIC [[1]](https://example.com) test</eos>")==="AMBIC test","sanitizer failed in JS harness");
let replayEnded=null;lastReplayableAudio=new ArrayBuffer(4);playContext={resume:async()=>{},createBuffer:()=>({getChannelData:()=>new Float32Array(2)}),createBufferSource:()=>({connect(){},start(){},set onended(fn){replayEnded=fn},get onended(){return replayEnded}}),destination:{}};await onMessage({data:JSON.stringify({type:"audio.replay.available",configuration_id,turn_id:4,generation:9,replay_count:1,state_mutation:false})},browserGeneration,current);assert(!card.querySelector(".turn-replay"),"visible replay button was exposed");await onMessage({data:JSON.stringify({type:"audio.replay.request",configuration_id,turn_id:4,generation:9})},browserGeneration,current);assert(pendingVoiceReplay&&card.querySelector(".replay-status").textContent.includes("마지막 답변"),"voice replay was not activated on replay request");
await onMessage({data:JSON.stringify({type:"speech.start",turn_id:5,generation:9})},browserGeneration,current);const researchTurn=turnNode(5,browserGeneration);researchEvents.set(researchEventKey({configuration_id,generation:9,turn_id:5}),{terminal:false,phase:"authoritative_web"});applyResearchResult({configuration_id,generation:9,turn_id:5,status:"success",answer_origin:"external_authoritative_reference",primary_text:"Clean scientific answer [[1]] (https://example.com/source)</eos>",citations:external},browserGeneration);const supplement=researchTurn.querySelector(".reply").children.find(item=>item.className==="research-supplement");assert(supplement&&supplement.children[0].textContent==="웹 참고 자료"&&supplement.children[1].textContent==="Clean scientific answer","research supplement heading or sanitization incorrect");
})().catch(error=>{console.error(error);process.exit(1)});
"""
        result = run_node_harness(harness)
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_session_restart_and_stale_event_isolation(self):
        html = (ROOT / "src" / "voice_workflow_agent" / "static" / "index.html").read_text(encoding="utf-8")
        script = html.split("<script>", 1)[1].split("</script>", 1)[0]
        self.assertNotIn("create"+"ScriptProcessor", script)
        self.assertNotIn("Script"+"ProcessorNode", script)
        self.assertNotIn("on"+"audioprocess", script)
        self.assertIn('audioWorklet.addModule("/mic-capture-worklet.js")',script)
        self.assertIn('numberOfOutputs:0',script)
        for constraint in (
            '"echoCancellation"',
            '"noiseSuppression"',
            '"autoGainControl"',
        ):
            self.assertIn(constraint,script)
        self.assertIn("마이크 음성 신호 감지됨", script)
        harness = r"""
const assert=(ok,message)=>{if(!ok)throw new Error(message)};
class Element{constructor(){this.children=[];this.fields={};this.textContent="";this.disabled=false;this.hidden=false;this.removed=false;this.dataset={};this.options=[];this.attributes={};this.href=""}set innerHTML(v){for(const c of ["transcript","reply","turn-status","filler-status","server-operation","tools","turn-visual","stats","error"]){const item=new Element();item.textContent=c==="transcript"?"듣는 중…":"";this.fields[c]=item}}querySelector(s){return this.fields[s.slice(1)]}prepend(n){this.children.unshift(n)}replaceChildren(){this.children=[];this.options=this.children}appendChild(n){this.children.push(n);this.options=this.children}remove(){this.removed=true}addEventListener(){}setAttribute(name,value){this.attributes[name]=value;if(name==="href")this.href=value}}
const ids=Object.fromEntries(["start","stop","log","status","state","last-report-id","last-report-state","pending-report","export-report-docx","record-anomaly","export-report-markdown","export-report-json","export-report-csv","experiment-report-list","experiment-report-events","language-status","pipeline-mode","protocol-id","protocol-pdf","register-protocol","protocol-upload-status","protocol-readiness","protocol-revision","session-configuration-status","new-user","language-confirmation","procedure-title","procedure-meta","procedure-status","procedure-progress","procedure-step-title","procedure-instruction","procedure-warning","procedure-spoken-summary","repeat-step","next-step","voice-command-hint","procedure-visual","source-visual-state","source-filename","source-page-number","source-short-hash","voice-processing","voice-filler-status","voice-primary-status","procedure-source","procedure-timer","procedure-observation","procedure-handoff","procedure-audit"].map(x=>[x,new Element()]));
ids["pipeline-mode"].value="cascade";ids["protocol-id"].value="candidate-a-curated-development-v1";
globalThis.document={getElementById:id=>ids[id],createElement:()=>new Element()}; globalThis.location={protocol:"http:",host:"test"};
class WS{static OPEN=1;static CLOSING=2;constructor(){this.readyState=1;this.sent=[]}send(x){this.sent.push(x)}close(){this.readyState=3}}
globalThis.WebSocket=WS; Object.defineProperty(globalThis,"navigator",{value:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[]})}},configurable:true}); globalThis.AudioContext=class{};
""" + script + r"""
(async()=>{
renderState("IDLE");assert(visibleState==="IDLE"&&!ids.start.disabled&&ids.stop.disabled,"initial controls");
let modulePath=null,sourceTarget=null,workletNode=null,trackStopped=false,requestedConstraints=null;Object.defineProperty(globalThis,"navigator",{value:{mediaDevices:{getSupportedConstraints:()=>({echoCancellation:true,noiseSuppression:true,autoGainControl:true}),getUserMedia:async constraints=>(requestedConstraints=constraints,{getTracks:()=>[{stop(){trackStopped=true}}]})}},configurable:true});globalThis.AudioContext=class{constructor(){this.sampleRate=48000;this.destination={};this.state="running";this.audioWorklet={addModule:async path=>{modulePath=path}}}createMediaStreamSource(){return{connect(node){sourceTarget=node},disconnect(){}}}resume(){return Promise.resolve()}close(){this.state="closed";return Promise.resolve()}};globalThis.AudioWorkletNode=class{constructor(context,name,options){this.context=context;this.name=name;this.options=options;this.disconnected=false;this.port={onmessage:null,postMessage:()=>{}};workletNode=this}disconnect(){this.disconnected=true}};
sessionActive=true;pipelineMode="cascade";renderState("LISTENING");await ensureAudio(0);assert(requestedConstraints.audio.channelCount===1&&requestedConstraints.audio.echoCancellation===true&&requestedConstraints.audio.noiseSuppression===true&&requestedConstraints.audio.autoGainControl===true,"supported microphone preprocessing not requested");assert(modulePath==="/mic-capture-worklet.js"&&workletNode.name==="voice-workflow-mic-capture"&&workletNode.options.numberOfOutputs===0&&sourceTarget===workletNode,"AudioWorklet graph invalid");const loud=new Float32Array(960);loud.fill(.1);workletNode.port.onmessage({data:loud.buffer});assert(micSignalSeen&&ids.status.textContent.includes("마이크 음성 신호 감지됨"),"browser mic signal not diagnosed");const sentPcm=socket.sent.at(-1);assert(sentPcm instanceof ArrayBuffer&&sentPcm.byteLength===640,"cascade PCM was not resampled to 16 kHz int16");const firstNode=workletNode;await ensureAudio(0);assert(workletNode===firstNode,"duplicate worklet node created");sessionActive=false;await closeAudio();assert(trackStopped&&firstNode.disconnected&&firstNode.port.onmessage===null,"microphone resources not cleaned");socket=new WS();sessionActive=true;pipelineMode="cascade";let fallbackConstraints=null;navigator.mediaDevices.getSupportedConstraints=()=>({});const cascadeTrack={stop(){},getSettings:()=>({echoCancellation:true,noiseSuppression:false,autoGainControl:true})};navigator.mediaDevices.getUserMedia=async constraints=>(fallbackConstraints=constraints,{getTracks:()=>[cascadeTrack],getAudioTracks:()=>[cascadeTrack]});await ensureAudio(0);assert(fallbackConstraints.audio.channelCount===1&&!('echoCancellation' in fallbackConstraints.audio)&&!('noiseSuppression' in fallbackConstraints.audio)&&!('autoGainControl' in fallbackConstraints.audio),"unsupported optional constraints were made mandatory");const constraintEvent=JSON.parse(socket.sent.at(-1));assert(constraintEvent.type==="client.audio_constraints"&&constraintEvent.requested.echoCancellation===false&&constraintEvent.actual.echoCancellation===true&&constraintEvent.actual.noiseSuppression===false&&constraintEvent.actual.autoGainControl===true,"requested/actual audio constraint telemetry missing");const cascadeNode=workletNode,cascadeBlock=new Float32Array(960);cascadeNode.port.onmessage({data:cascadeBlock.buffer});const cascadePcm=socket.sent.at(-1);assert(cascadePcm instanceof ArrayBuffer&&cascadePcm.byteLength===640,"cascade PCM is not a 20 ms 16 kHz mono frame");sessionActive=false;await closeAudio();assert(cascadeNode.disconnected,"repeated microphone stop did not clean worklet");renderState("IDLE");
const oldSocket=socket;await onMessage({data:JSON.stringify({type:"speech.start",turn_id:1})},0,oldSocket);await onMessage({data:JSON.stringify({type:"transcript",turn_id:1,text:"old question"})},0,oldSocket);await onMessage({data:JSON.stringify({type:"reply.delta",turn_id:1,text:"old answer"})},0,oldSocket);const oldNode=ids.log.children[0];
await stopSession();assert(visibleState==="IDLE"&&ids.log.children.length===1,"stop state or transcript");socket=new WS();let audioInitializations=0;ensureAudio=async()=>{audioInitializations++};await startSession();assert(visibleState==="CONNECTING"&&ids.start.disabled&&!ids.stop.disabled,"start not connecting");assert(ids.log.children.length===0&&turns.size===0,"start reset incomplete");
const requestedStart=JSON.parse(socket.sent.at(-1));assert(JSON.stringify(requestedStart)===JSON.stringify({type:"session.start",configuration_id:1,mode:"cascade",language:"ko",protocol_id:"candidate-a-curated-development-v1"}),"browser start payload shape changed");assert(audioInitializations===0&&!sessionActive,"microphone or session activated before server acknowledgement");
const newSocket=socket,generation=sessionGeneration;await onMessage({data:JSON.stringify({type:"session.ready",configuration_id:999,mode:"cascade",language:"ko",protocol_id:"candidate-a-curated-development-v1",revision_id:"fixture-test"})},generation,newSocket);assert(audioInitializations===0&&!sessionActive&&visibleState==="CONNECTING","stale acknowledgement made UI ready");await onMessage({data:JSON.stringify({type:"session.ready",configuration_id:1,mode:"cascade",language:"ko",protocol_id:"candidate-a-curated-development-v1",revision_id:"fixture-test"})},generation,newSocket);assert(audioInitializations===1&&sessionActive&&visibleState==="LISTENING","accepted configuration did not activate microphone and UI");assert(acceptedSessionConfiguration.protocol_id==="candidate-a-curated-development-v1"&&acceptedSessionConfiguration.revision_id==="fixture-test"&&ids["session-configuration-status"].textContent.includes("서버 확인 완료"),"accepted protocol configuration not rendered");await onMessage({data:JSON.stringify({type:"session.started",state:"IDLE",pipeline:"cascade"})},generation,newSocket);assert(visibleState==="LISTENING","legacy session.started changed readiness");await onMessage({data:JSON.stringify({type:"turn.processing",turn_id:1})},generation,newSocket);assert(visibleState==="THINKING","processing not thinking");
const curated0={attached:true,protocol_id:"candidate-a-curated-development-v1",revision_id:"fixture-test",display_name:"In-gel digestion protocol for protein identification",development_only:true,readiness_status:"analysis_required",active:false,current_step_label:null,current_step_id:null,total_steps:25,at_final_step:false,block_reason:null,revision:0,source_page_refs:[],visual_assets:[],visual_status:"unavailable",critical_warning_texts:[],display_summary:null};
await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id:1,action:"attached",state:curated0})},generation,newSocket);assert(ids["procedure-title"].textContent===curated0.display_name&&ids["procedure-meta"].textContent.includes("개발용")&&ids["procedure-status"].textContent.includes("대기"),`attached curated fixture not rendered truthfully: ${ids["procedure-title"].textContent}|${ids["procedure-meta"].textContent}|${ids["procedure-status"].textContent}|${curatedStateRevision}|${JSON.stringify(acceptedSessionConfiguration)}|${generation}/${sessionGeneration}|${socket===newSocket}`);
const curated1={...curated0,active:true,current_step_label:"1",current_step_id:"step-1",revision:1};await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id:1,action:"start",state:curated1})},generation,newSocket);assert(ids["procedure-progress"].textContent.includes("1/25")&&ids["procedure-status"].textContent.includes("진행 중"),"active curated step not rendered");await onMessage({data:JSON.stringify({type:"procedure.state",state:{attached:false}})},generation,newSocket);assert(ids["procedure-title"].textContent===curated1.display_name&&ids["procedure-progress"].textContent.includes("1/25"),"unattached approved-procedure projection erased active curated state");
const stale={...curated1,current_step_label:"25",current_step_id:"step-25",revision:0};await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id:1,action:"next",state:stale})},generation,newSocket);assert(curatedProtocolState.current_step_label==="1","stale curated revision overwrote current state");await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id:999,action:"next",state:{...curated1,current_step_label:"2",current_step_id:"step-2",revision:2}})},generation,newSocket);assert(curatedProtocolState.current_step_label==="1","wrong configuration curated state accepted");
await onMessage({data:JSON.stringify({type:"session.language_state",mode:"manual",language:"ko"})},generation,newSocket);assert(ids["language-status"].textContent.includes("한국어"),"korean state missing");
const ps={attached:true,procedure_id:"demo",title:"FICTIONAL NON-OPERATIONAL Demo",version:"1",status:"active",total_step_count:2,completed_step_count:0,current_step_number:1,current_step_id:"one",current_step_title:"One",approved_current_instruction:"Approved fictional instruction."};
await onMessage({data:JSON.stringify({type:"procedure.state",state:ps})},generation,newSocket);assert(ids["procedure-title"].textContent===ps.title&&ids["procedure-instruction"].textContent===ps.approved_current_instruction,"procedure event not rendered");
const blocked={...ps,status:"blocked_for_handoff",handoff:{report_id:"SR-20260722-A1B2C3",blocked_step_id:"one"}};
await onMessage({data:JSON.stringify({type:"procedure.state",state:blocked})},generation,newSocket);assert(procedureState.status==="blocked_for_handoff"&&ids["procedure-status"].textContent.includes("진행 차단")&&ids["procedure-handoff"].textContent.includes("SR-20260722-A1B2C3"),"blocked workflow not rendered");
await onMessage({data:JSON.stringify({type:"procedure.state",state:ps})},generation,newSocket);
await onMessage({data:JSON.stringify({type:"reply.delta",turn_id:1,text:"completed step two"})},generation,newSocket);assert(procedureState.completed_step_count===0,"reply text mutated procedure");
await onMessage({data:JSON.stringify({type:"procedure.state",state:{attached:true,title:"bad"}})},generation,newSocket);assert(procedureState.completed_step_count===0,"malformed procedure state accepted");
for(const bad of [
 {...ps,current_step_number:2},
 {...ps,current_step_id:""},
 {...ps,completed_step_count:2},
 {...ps,status:"completed",completed_step_count:2},
 {...ps,status:"completed",completed_step_count:2,current_step_number:null,current_step_id:null,current_step_title:null,approved_current_instruction:"not null"}
]){await onMessage({data:JSON.stringify({type:"procedure.state",state:bad})},generation,newSocket);assert(procedureState.status==="active"&&procedureState.completed_step_count===0,"inconsistent procedure state accepted");}
const done={...ps,status:"completed",completed_step_count:2,current_step_number:null,current_step_id:null,current_step_title:null,approved_current_instruction:null};
await onMessage({data:JSON.stringify({type:"procedure.state",state:done})},generation,newSocket);assert(procedureState.status==="completed","canonical completed state rejected");
await onMessage({data:JSON.stringify({type:"procedure.state",state:{attached:false}})},generation,newSocket);assert(procedureState.attached===false&&ids["procedure-title"].textContent.includes("없음"),"procedure detach not rendered");
await onMessage({data:JSON.stringify({type:"error",message:"invalid request"})},generation,newSocket);assert(ids["language-status"].textContent.includes("한국어"),"failed request did not preserve fixed korean language UI");assert(visibleState==="ERROR","failed request did not use safe error state");
const authoritativeDisplay="Full canonical development-fixture step instruction.";const shortSpeech="Short control acknowledgement.";await onMessage({data:JSON.stringify({type:"speech.start",turn_id:1,generation:10})},generation,newSocket);await onMessage({data:JSON.stringify({type:"transcript",turn_id:1,generation:10,text:"new question"})},generation,newSocket);await onMessage({data:JSON.stringify({type:"reply.delta",turn_id:1,generation:10,text:authoritativeDisplay,speech_text:shortSpeech})},generation,newSocket);assert(turnNode(1,generation).querySelector(".reply").textContent===authoritativeDisplay+" "&&!turnNode(1,generation).querySelector(".reply").textContent.includes(shortSpeech),"curated display text was not rendered independently of speech text");
await onMessage({data:JSON.stringify({type:"research.state",configuration_id:1,turn_id:1,generation:10,status:"running",phase:"authoritative_web"})},generation,newSocket);assert(turnNode(1,generation).querySelector(".filler-status").textContent.includes("외부 권위 근거"),"research state was not attached to its Turn");await onMessage({data:JSON.stringify({type:"speech.start",turn_id:2,generation:11})},generation,newSocket);
await onMessage({data:JSON.stringify({type:"research.result",configuration_id:1,turn_id:1,generation:10,status:"success",primary_text:"권위 자료의 보충 설명",answer_origin:"external_authoritative_reference",citations:[{title:"Authoritative source",domain:"osha.gov",canonical_url:"https://osha.gov/laboratory"}],limitations:["non-protocol"]})},generation,newSocket);const researchBlock=turnNode(1,generation).querySelector(".reply").children.find(item=>item.className==="research-supplement");assert(researchBlock&&researchBlock.children[0].textContent==="웹 참고 자료"&&turns.size===1&&!turnNode(1,generation).querySelector(".filler-status").textContent,"late research did not patch the originating historical Turn");
const acceptedResearchText=researchBlock.children[1].textContent;await onMessage({data:JSON.stringify({type:"research.result",configuration_id:1,turn_id:1,generation:10,status:"failed",terminal_status:"failed",limitation:"late duplicate"})},generation,newSocket);assert(researchBlock.children[1].textContent===acceptedResearchText,"a terminal research result accepted a later terminal event");
turnNode(2,generation);await onMessage({data:JSON.stringify({type:"research.state",configuration_id:1,turn_id:2,generation:11,status:"running",phase:"supplemental_model"})},generation,newSocket);assert(turnNode(2,generation).querySelector(".filler-status").textContent.includes("일반 배경"),"supplemental progress was not labelled");await onMessage({data:JSON.stringify({type:"research.result",configuration_id:1,turn_id:2,generation:11,status:"success",terminal_status:"success",primary_text:"일반적인 과학 배경 설명",answer_origin:"supplemental_model_knowledge",citations:[]})},generation,newSocket);const supplementalBlock=turnNode(2,generation).querySelector(".reply").children.find(item=>item.className==="research-supplement");assert(supplementalBlock&&supplementalBlock.children[0].textContent==="일반 참고 설명"&&!turnNode(2,generation).querySelector(".filler-status").textContent,"supplemental result was not separately labelled or terminal");
const draft={location:"Lab A",summary:"spill",urgency:"urgent",exposure_status:"unknown",material_or_equipment:"acetone"};
await onMessage({data:JSON.stringify({type:"tool.result",turn_id:1,generation:10,round:0,tool:"create_safety_report",status:"awaiting_user_confirmation",report:draft})},generation,newSocket);assert(ids["pending-report"].hidden===true,"orphan tool result was rendered");
await onMessage({data:JSON.stringify({type:"tool.call",turn_id:1,generation:10,round:0,tool:"create_safety_report",status:"calling",report:draft})},generation,newSocket);await onMessage({data:JSON.stringify({type:"tool.result",turn_id:1,generation:10,round:0,tool:"create_safety_report",status:"awaiting_user_confirmation",report:draft})},generation,newSocket);assert(ids["pending-report"].hidden===false&&ids["pending-report"].textContent.includes("acetone"),"draft not visible after a real tool call");
await onMessage({data:JSON.stringify({type:"tool.call",turn_id:1,generation:10,round:1,tool:"create_safety_report",status:"submitting",report:draft})},generation,newSocket);assert(ids["last-report-state"].textContent==="보고서 제출 중","submitting state missing");
await onMessage({data:JSON.stringify({type:"tool.result",turn_id:1,generation:10,round:1,tool:"create_safety_report",status:"submission_failed",report:draft})},generation,newSocket);assert(ids["pending-report"].hidden===false&&ids["last-report-state"].textContent.includes("다시 승인하거나 취소"),"failed draft hidden");
await onMessage({data:JSON.stringify({type:"tool.call",turn_id:1,generation:10,round:2,tool:"create_safety_report",status:"calling",report:draft})},generation,newSocket);await onMessage({data:JSON.stringify({type:"tool.result",turn_id:1,generation:10,round:2,tool:"create_safety_report",status:"cancelled",report:draft})},generation,newSocket);assert(ids["pending-report"].hidden===true&&ids["last-report-id"].textContent==="아직 접수된 보고 없음","cancel did not reset draft UI");
await onMessage({data:JSON.stringify({type:"tool.call",turn_id:1,generation:10,round:3,tool:"create_safety_report",status:"calling",report:draft})},generation,newSocket);await onMessage({data:JSON.stringify({type:"tool.result",turn_id:1,generation:10,round:3,tool:"create_safety_report",status:"confirmed",report:draft,report_id:"SR-20260722-A1B2C3",report_status:"queued_for_handoff",elapsed_ms:2})},generation,newSocket);const newNode=ids.log.children[0];assert(newNode!==oldNode&&newNode.querySelector(".transcript").textContent==="new question","transcript reset");assert(newNode.querySelector(".tools").textContent.includes("Tool · 안전 보고 접수"),"truthful tool result missing");assert(ids["last-report-id"].textContent==="SR-20260722-A1B2C3"&&ids["last-report-state"].textContent==="관리자 인계 대기"&&ids["pending-report"].hidden===true,"report card missing");
await onMessage({data:JSON.stringify({type:"report.status",report_id:"SR-20260722-A1B2C3",status:"success",report_status:"handoff_ready",attempts:1})},generation,newSocket);assert(ids["last-report-state"].textContent.includes("관리자 인계문 준비 완료")&&reportPollHandle===null,"automatic report status not rendered");
await onMessage({data:JSON.stringify({type:"experiment.report.state",configuration_id:1,turn_id:1,generation:10,report:{report_id:"ER-1234567890ABCDEF1234",status:"in_progress",event_count:3,anomaly_count:1,blocker_count:0,reports:[{report_id:"ER-1234567890ABCDEF1234",status:"in_progress"}],events:[{event_type:"anomaly_recorded",step_label:"3",created_at:"2026-07-26T00:00:00Z",user_wording:"색이 변했어요",payload:{timer:{remaining_seconds:12}}}]}})},generation,newSocket);assert(ids["last-report-id"].textContent==="ER-1234567890ABCDEF1234"&&ids["last-report-state"].textContent.includes("이상 1")&&ids["export-report-markdown"].href.endsWith(".md")&&ids["export-report-json"].href.endsWith(".json")&&ids["export-report-csv"].href.endsWith(".csv")&&ids["export-report-docx"].href.endsWith(".docx")&&ids["export-report-json"].attributes["aria-disabled"]==="false"&&ids["experiment-report-list"].children.length===1&&ids["experiment-report-events"].children.length===1,"experiment report state or exports missing");
await onMessage({data:JSON.stringify({type:"experiment.report.state",configuration_id:1,turn_id:1,generation:9,report:{report_id:"ER-STALE000000000000000",status:"completed",event_count:99,anomaly_count:99,blocker_count:0}})},generation,newSocket);assert(ids["last-report-id"].textContent==="ER-1234567890ABCDEF1234","stale report event replaced the current report");
await onMessage({data:JSON.stringify({type:"tool.call",turn_id:1,generation:10,round:4,tool:"start_step_timer",status:"calling"})},generation,newSocket);await onMessage({data:JSON.stringify({type:"tool.result",turn_id:1,generation:10,round:4,tool:"start_step_timer",status:"error",code:"timer_not_configured"})},generation,newSocket);assert(newNode.querySelector(".tools").textContent.includes("현재 단계에 타이머 없음"),"tool error reason hidden");let ended;playContext={resume:async()=>{},createBuffer:()=>({getChannelData:()=>new Float32Array(1)}),createBufferSource:()=>({connect(){},start(){},set onended(fn){ended=fn},get onended(){return ended}}),destination:{}};activeTurn=1;queued.set(0,new ArrayBuffer(2));await pump(generation);assert(visibleState==="SPEAKING","playback not speaking");await onMessage({data:JSON.stringify({type:"audio.complete",turn_id:1})},generation,newSocket);await onMessage({data:JSON.stringify({type:"turn.done",turn_id:1,route:"brain",timings_ms:{stt:1,first_audio_ms:2,total_ms:3},segment_count:1,output_frames:1})},generation,newSocket);assert(newNode.querySelector(".stats").textContent.includes("경로 brain")&&newNode.querySelector(".stats").textContent.includes("첫 음성 2 ms"),"server route or first audio missing");assert(visibleState==="SPEAKING","done changed queued playback");ended();await Promise.resolve();assert(visibleState==="LISTENING","drained playback not listening");await onMessage({data:JSON.stringify({type:"turn.done",turn_id:1,route:"deterministic_emergency",timings_ms:{stt:1,total_ms:3},segment_count:0,output_frames:0})},generation,newSocket);assert(newNode.querySelector(".stats").textContent.includes("경로 deterministic_emergency")&&newNode.querySelector(".stats").textContent.includes("첫 음성 측정 안 됨")&&!newNode.querySelector(".stats").textContent.includes("undefined"),"missing first audio display unsafe");const lateEnded=ended;
await onMessage({data:JSON.stringify({type:"playback.completed",pipeline:"cascade",turn_id:1,playback_completion_ms:1234})},generation,newSocket);assert(newNode.querySelector(".stats").textContent.includes("재생 완료 1234 ms"),"playback completion metric missing");
sessionActive=true;playContext={currentTime:0,resume:async()=>{},createBuffer:(_,length,rate)=>({duration:length/rate,getChannelData:()=>new Float32Array(length)}),createBufferSource:()=>({connect(){},start(){},stop(){},disconnect(){},set onended(fn){},get onended(){return null}}),destination:{}};
await stopSession();lateEnded();await Promise.resolve();assert(visibleState==="IDLE","late playback callback changed state");
await onMessage({data:JSON.stringify({type:"reply.delta",turn_id:1,text:"late"})},0,oldSocket);assert(newNode.querySelector(".reply").textContent===authoritativeDisplay+" ","stale text accepted");
for(const state of ["IDLE","CONNECTING","LISTENING","THINKING","SPEAKING","ERROR"]){renderState(state);await stopSession();assert(visibleState==="IDLE"&&!ids.start.disabled&&ids.stop.disabled,"stop from "+state);}
await onMessage({data:JSON.stringify({type:"state.changed",state:"AGENT_SPEAKING"})},generation,newSocket);assert(visibleState==="IDLE","old speaking event accepted");
socket=new WS();ids["pipeline-mode"].value="cascade";ids["protocol-id"].value="";await startSession();const unselectedRequest=JSON.parse(socket.sent.at(-1));await onMessage({data:JSON.stringify({type:"session.configuration_required",configuration_id:unselectedRequest.configuration_id,mode:"cascade",language:"ko",protocol_id:null,reason:"protocol_selection_required"})},sessionGeneration,socket);assert(!sessionActive&&acceptedSessionConfiguration===null&&visibleState==="IDLE"&&ids["session-configuration-status"].textContent.includes("정확한 프로토콜"),"mode-only request masqueraded as ready");await stopSession();
socket=null;const reconnectPromise=init(sessionGeneration),reconnectSocket=socket;reconnectSocket.onopen();await reconnectPromise;acceptedSessionConfiguration={configuration_id:999,mode:"cascade",language:"ko",protocol_id:"candidate-a-curated-development-v1"};sessionActive=true;renderCuratedProtocolState({configuration_id:999,state:{...curated0,revision:0}});renderState("LISTENING");reconnectSocket.onclose();await Promise.resolve();assert(!sessionActive&&acceptedSessionConfiguration===null&&visibleState==="ERROR"&&ids["session-configuration-status"].textContent.includes("다시 선택")&&curatedProtocolState.attached===false&&ids["procedure-title"].textContent.includes("없음"),"reconnect silently retained accepted configuration or curated state");await stopSession();
for(let i=0;i<3;i++){socket=new WS();ids["pipeline-mode"].value="cascade";ids["protocol-id"].value="candidate-a-curated-development-v1";await startSession();assert(visibleState==="CONNECTING","restart connecting");const request=JSON.parse(socket.sent.at(-1));await onMessage({data:JSON.stringify({type:"session.ready",configuration_id:request.configuration_id,mode:"cascade",language:"ko",protocol_id:"candidate-a-curated-development-v1",revision_id:"fixture-test"})},sessionGeneration,socket);assert(visibleState==="LISTENING"&&ids.start.disabled&&!ids.stop.disabled&&ids.status.textContent==="듣고 있습니다…","restart active controls");await stopSession();assert(visibleState==="IDLE"&&!ids.start.disabled&&ids.stop.disabled&&ids.status.textContent==="준비됨 · 세션 시작을 한 번 눌러주세요.","restart idle controls");}
})().catch(e=>{console.error(e);process.exit(1)});
"""
        result = run_node_harness(harness)
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_cascade_generation_clear_and_provisional_turn_cleanup(self):
        html=(
            ROOT/"src"/"voice_workflow_agent"/"static"/"index.html"
        ).read_text(encoding="utf-8")
        script=html.split("<script>",1)[1].split("</script>",1)[0]
        for forbidden in (
            "127.0.0.1:8000","localhost:8000","file://",
            "/home/student/protocol-test-files",
        ):
            self.assertNotIn(forbidden,script)
        self.assertNotIn('createElement("iframe")',script)
        self.assertIn('createElement("img")',script)
        harness=r"""
const assert=(ok,message)=>{if(!ok)throw new Error(message)};
class Element{constructor(){this.children=[];this.fields={};this.textContent="";this.disabled=false;this.hidden=false;this.removed=false;this.dataset={};this.options=[]}set innerHTML(v){for(const c of ["transcript","reply","turn-status","filler-status","server-operation","tools","turn-visual","stats","error"]){const item=new Element();item.textContent=c==="transcript"?"듣는 중…":"";this.fields[c]=item}}querySelector(s){return this.fields[s.slice(1)]}prepend(n){this.children.unshift(n)}replaceChildren(){this.children=[];this.options=this.children}appendChild(n){this.children.push(n);this.options=this.children}remove(){this.removed=true}addEventListener(){}setAttribute(){}}
const ids=Object.fromEntries(["start","stop","log","status","state","last-report-id","last-report-state","pending-report","language-status","language-mode","manual-language","pipeline-mode","protocol-id","protocol-pdf","register-protocol","protocol-upload-status","protocol-readiness","protocol-revision","session-configuration-status","research-text-capability","supplemental-knowledge-capability","research-image-capability","generated-visual-capability","audio-processing-capability","new-user","language-confirmation","procedure-title","procedure-meta","procedure-status","procedure-progress","procedure-step-title","procedure-instruction","procedure-warning","procedure-spoken-summary","repeat-step","next-step","voice-command-hint","procedure-visual","source-visual-state","source-filename","source-page-number","source-short-hash","voice-processing","voice-filler-status","voice-primary-status","procedure-source","procedure-timer","procedure-observation","procedure-handoff","procedure-audit"].map(x=>[x,new Element()]));
ids["language-mode"].value="manual";ids["manual-language"].value="ko";ids["pipeline-mode"].value="cascade";ids["protocol-id"].value="candidate-a-curated-development-v1";
globalThis.document={getElementById:id=>ids[id],createElement:()=>new Element()};globalThis.location={protocol:"http:",host:"test"};
class WS{static OPEN=1;static CLOSING=2;constructor(){this.readyState=1;this.sent=[]}send(value){this.sent.push(value)}close(){this.readyState=3}}
globalThis.WebSocket=WS;Object.defineProperty(globalThis,"navigator",{value:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[]})}},configurable:true});globalThis.AudioContext=class{};
"""+script+r"""
(async()=>{
 const current=socket,browserGeneration=sessionGeneration;
 acceptedSessionConfiguration={configuration_id:41,mode:"cascade",language:"ko",protocol_id:"candidate-a-curated-development-v1"};sessionActive=true;pipelineMode="cascade";
 assert(renderResearchCapabilities({external_text:{status:"enabled",authority_profile:"candidate_a",allowed_domain_count:5},supplemental_model:{status:"enabled",authority:"supplemental_model_knowledge"},web_image:{status:"enabled"},generated_visual:{status:"disabled"}})&&ids["research-text-capability"].textContent.includes("candidate_a")&&ids["supplemental-knowledge-capability"].textContent.includes("권위 근거 아님")&&ids["research-image-capability"].textContent.includes("사용 가능")&&ids["generated-visual-capability"].textContent.includes("사용 안 함"),"non-secret research capability state was not rendered");
 await onMessage({data:JSON.stringify({type:"barge_in_candidate",turn_id:99,generation:9,voiced_frames:4,total_frames:6})},browserGeneration,current);await onMessage({data:JSON.stringify({type:"barge_in_rejected",turn_id:99,generation:9,reason:"minimum_voiced_frames",voiced_frames:5,total_frames:8})},browserGeneration,current);assert(turns.size===0&&provisionalTurns.size===0&&ids.log.children.length===0,"noise-only barge candidate left a Turn card");
 let stoppedFirst=0,stoppedSecond=0,created=0;
 const firstSource={onended:()=>{},stop(){stoppedFirst++},disconnect(){}};
 const secondSource={onended:()=>{},stop(){stoppedSecond++},disconnect(){}};
 playContext={state:"running",resume:async()=>{},close:async()=>{},destination:{},createBuffer:()=>({getChannelData:()=>new Float32Array(1)}),createBufferSource:()=>{created++;return{onended:null,connect(){},start(){},stop(){},disconnect(){}}}};
 micWorkletNode={port:{onmessage:()=>{},postMessage(){}},disconnect(){}};const microphone=micWorkletNode;
 await onMessage({data:JSON.stringify({type:"speech.start",turn_id:1,generation:10})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"transcript",turn_id:1,generation:10,text:"A M B I C가 뭐야"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"reply.delta",turn_id:1,generation:10,text:"Canonical display text",transcript_correction_note:"현재 단계의 AMBIC을 말씀하신 것으로 이해했어요."})},browserGeneration,current);
 assert(turnNode(1,browserGeneration).querySelector(".transcript").textContent==="A M B I C가 뭐야"&&turnNode(1,browserGeneration).querySelector(".reply").textContent.includes("AMBIC"),"raw transcript or bounded correction note was lost");
 const acceptedReply=turnNode(1,browserGeneration).querySelector(".reply").textContent;
 activeSource=firstSource;playing=true;queued.set(0,new ArrayBuffer(2));receiving={turn_id:1,generation:10,segment_index:1};receivedFrames=[new ArrayBuffer(2)];
 let gainValue=1;cascadeGain={gain:{value:1,setValueAtTime(value){gainValue=value}}};
 await onMessage({data:JSON.stringify({type:"barge_in_candidate",turn_id:1,generation:10})},browserGeneration,current);assert(gainValue===.04&&cascadeInterruption.state==="candidate"&&turns.size===1,"matching candidate was not provisionally ducked or created a Turn");
 await onMessage({data:JSON.stringify({type:"barge_in_rejected",turn_id:1,generation:10})},browserGeneration,current);assert(gainValue===1&&cascadeInterruption.state==="idle"&&activeSource===firstSource,"rejected candidate did not safely resume matching playback");
 await onMessage({data:JSON.stringify({type:"barge_in_candidate",turn_id:1,generation:9})},browserGeneration,current);assert(gainValue===1&&cascadeInterruption.state==="idle","stale candidate ducked current playback");
 await onMessage({data:JSON.stringify({type:"barge_in_candidate",turn_id:1,generation:10})},browserGeneration,current);assert(gainValue===.04,"committed candidate was not ducked");
 await onMessage({data:JSON.stringify({type:"cascade.playback.clear",configuration_id:41,turn_id:1,generation:9,revision:1,state:"cancelled",superseding_turn_id:2,superseding_generation:11,reason:"confirmed_speech"})},browserGeneration,current);
 assert(stoppedFirst===0&&activeTurn===1&&queued.size===1,"stale clear changed active audio");
 const clear={type:"cascade.playback.clear",configuration_id:41,turn_id:1,generation:10,revision:1,state:"cancelled",superseding_turn_id:2,superseding_generation:11,reason:"confirmed_speech"};
 await onMessage({data:JSON.stringify(clear)},browserGeneration,current);
 const interrupted=turnNode(1,browserGeneration);
 assert(stoppedFirst===1&&queued.size===0&&receiving===null&&activeTurn===null&&activeCascadeGeneration===null,"accepted clear did not stop exact Cascade playback");
 assert(interrupted.querySelector(".transcript").textContent==="A M B I C가 뭐야"&&interrupted.querySelector(".reply").textContent===acceptedReply&&interrupted.querySelector(".error").textContent==="중단됨","interrupted terminal card lost accepted content");
 assert(micWorkletNode===microphone&&sessionActive,"barge-in stopped microphone or session");
 await pump(browserGeneration);assert(created===0,"pump rescheduled stale queued audio");
 await onMessage({data:JSON.stringify(clear)},browserGeneration,current);assert(stoppedFirst===1,"duplicate clear was not idempotent");
 await onMessage({data:JSON.stringify({type:"reply.delta",turn_id:1,generation:10,text:"late"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"audio.segment.start",turn_id:1,generation:10,segment_index:2,frame_count:1})},browserGeneration,current);
 await onMessage({data:new ArrayBuffer(2)},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"audio.complete",turn_id:1,generation:10})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.done",turn_id:1,generation:10,route:"curated_protocol",timings_ms:{},segment_count:1})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"playback.completed",turn_id:1,generation:10,playback_completion_ms:99})},browserGeneration,current);
 assert(interrupted.querySelector(".reply").textContent===acceptedReply&&interrupted.querySelector(".stats").textContent===""&&interrupted.querySelector(".error").textContent==="중단됨"&&queued.size===0,"late stale event revived interrupted turn");
 await onMessage({data:JSON.stringify({type:"speech.start",turn_id:2,generation:11})},browserGeneration,current);activeSource=secondSource;playing=true;queued.set(0,new ArrayBuffer(2));
 await onMessage({data:JSON.stringify(clear)},browserGeneration,current);assert(activeTurn===2&&activeCascadeGeneration===11&&stoppedSecond===0&&queued.size===1,"stale clear removed newer generation");
 await onMessage({data:JSON.stringify({type:"transcript",turn_id:2,generation:11,text:"현재 단계 알려줘"})},browserGeneration,current);assert(turnNode(2,browserGeneration).querySelector(".transcript").textContent==="현재 단계 알려줘","superseding utterance was not accepted");
 clearPlayback();
 await onMessage({data:JSON.stringify({type:"speech.start",turn_id:3,generation:12})},browserGeneration,current);assert(!turns.has(`${browserGeneration}:3`)&&provisionalTurns.has(`${browserGeneration}:3`),"speech onset created a permanent card");await onMessage({data:JSON.stringify({type:"speech.rejected",turn_id:3,generation:12,reason:"minimum_voiced_frames"})},browserGeneration,current);assert(!turns.has(`${browserGeneration}:3`)&&!provisionalTurns.has(`${browserGeneration}:3`),"explicit no-speech did not remove provisional state");
 await onMessage({data:JSON.stringify({type:"speech.start",turn_id:4,generation:13})},browserGeneration,current);await onMessage({data:JSON.stringify({type:"speech.rejected",turn_id:3,generation:12,reason:"minimum_voiced_frames"})},browserGeneration,current);assert(provisionalTurns.has(`${browserGeneration}:4`)&&!turns.has(`${browserGeneration}:4`),"stale rejection removed active provisional state");
 await onMessage({data:JSON.stringify({type:"transcript",turn_id:4,generation:13,text:"accepted"})},browserGeneration,current);const activeCard=turnNode(4,browserGeneration);
 await onMessage({data:JSON.stringify({type:"speech.start",turn_id:5,generation:14})},browserGeneration,current);await onMessage({data:JSON.stringify({type:"session.stopped"})},browserGeneration,current);assert(!turns.has(`${browserGeneration}:5`)&&!provisionalTurns.has(`${browserGeneration}:5`),"explicit session stop did not remove provisional state");
 sessionActive=true;await onMessage({data:JSON.stringify({type:"speech.start",turn_id:6,generation:15})},browserGeneration,current);current.onclose();await Promise.resolve();assert(!turns.has(`${browserGeneration}:6`)&&!provisionalTurns.has(`${browserGeneration}:6`)&&turns.has(`${browserGeneration}:4`),"disconnect did not remove only provisional state");
 assert(!activeCard.removed&&activeCard.querySelector(".transcript").textContent==="accepted","disconnect removed accepted transcript card");
})().catch(error=>{console.error(error);process.exit(1)});
"""
        result=run_node_harness(harness)
        self.assertEqual(result.returncode,0,result.stderr)

    def test_turn_card_applies_server_revisions_monotonically(self):
        html=(
            ROOT/"src"/"voice_workflow_agent"/"static"/"index.html"
        ).read_text(encoding="utf-8")
        script=html.split("<script>",1)[1].split("</script>",1)[0]
        harness=r"""
const assert=(ok,message)=>{if(!ok)throw new Error(message)};
class Element{constructor(){this.children=[];this.fields={};this.textContent="";this.disabled=false;this.hidden=false;this.removed=false;this.dataset={};this.options=[]}set innerHTML(v){for(const c of ["transcript","reply","turn-status","filler-status","server-operation","tools","turn-visual","stats","error"]){const item=new Element();item.textContent=c==="transcript"?"듣는 중…":"";this.fields[c]=item}}querySelector(s){return this.fields[s.slice(1)]}prepend(n){this.children.unshift(n)}replaceChildren(){this.children=[];this.options=this.children}appendChild(n){this.children.push(n);this.options=this.children}remove(){this.removed=true}addEventListener(){}setAttribute(){}}
const ids=Object.fromEntries(["start","stop","log","status","state","last-report-id","last-report-state","pending-report","language-status","language-mode","manual-language","pipeline-mode","protocol-id","protocol-pdf","register-protocol","protocol-upload-status","protocol-readiness","protocol-revision","session-configuration-status","new-user","language-confirmation","procedure-title","procedure-meta","procedure-status","procedure-progress","procedure-step-title","procedure-instruction","procedure-warning","procedure-spoken-summary","repeat-step","next-step","voice-command-hint","procedure-visual","source-visual-state","source-filename","source-page-number","source-short-hash","voice-processing","voice-filler-status","voice-primary-status","procedure-source","procedure-timer","procedure-observation","procedure-handoff","procedure-audit"].map(x=>[x,new Element()]));
ids["language-mode"].value="manual";ids["manual-language"].value="ko";ids["pipeline-mode"].value="cascade";ids["protocol-id"].value="candidate-a-curated-development-v1";
globalThis.document={getElementById:id=>ids[id],createElement:()=>new Element()};globalThis.location={protocol:"http:",host:"test"};
class WS{static OPEN=1;static CLOSING=2;constructor(){this.readyState=1;this.sent=[]}send(value){this.sent.push(value)}close(){this.readyState=3}}
globalThis.WebSocket=WS;Object.defineProperty(globalThis,"navigator",{value:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[]})}},configurable:true});globalThis.AudioContext=class{};
"""+script+r"""
(async()=>{
 const current=socket,browserGeneration=sessionGeneration,configuration_id=51,base={configuration_id,turn_id:1,generation:10};
 acceptedSessionConfiguration={configuration_id,mode:"cascade",language:"ko",protocol_id:"candidate-a-curated-development-v1"};sessionActive=true;pipelineMode="cascade";
 await onMessage({data:JSON.stringify({type:"speech.start",turn_id:1,generation:10})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:1,state:"listening"})},browserGeneration,current);
 assert(!turns.has(`${browserGeneration}:1`)&&provisionalTurns.has(`${browserGeneration}:1`),"listening created a permanent card");
 await onMessage({data:JSON.stringify({type:"transcript",turn_id:1,generation:10,text:"현재 단계 알려줘"})},browserGeneration,current);
 const node=turnNode(1,browserGeneration);
 await onMessage({data:JSON.stringify({type:"reply.delta",turn_id:1,generation:10,text:"Canonical display",speech_text:"Short speech"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:3,state:"transcribing"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:2,state:"routing"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:3,state:"routing"})},browserGeneration,current);
 assert(node.querySelector(".turn-status").textContent==="음성 인식 중…","lower or duplicate revision regressed state");
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:4,state:"routing"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:5,state:"checking_protocol",route:"curated_protocol"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:6,state:"synthesizing",route:"curated_protocol"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:7,state:"playing",route:"curated_protocol",timings_ms:{time_to_playable_audio:12}})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:8,state:"complete",route:"curated_protocol",timings_ms:{playback_completion:20}})},browserGeneration,current);
 assert(node.querySelector(".turn-status").textContent==="완료 · 개발용 절차","complete state missing");
 assert(node.querySelector(".transcript").textContent==="현재 단계 알려줘"&&node.querySelector(".reply").textContent==="Canonical display "&&!node.querySelector(".reply").textContent.includes("Short speech"),"progress lost transcript/display separation");
 await onMessage({data:JSON.stringify({type:"turn.state",...base,revision:9,state:"playing",route:"curated_protocol"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,configuration_id:99,revision:20,state:"error"})},browserGeneration,current);
 await onMessage({data:JSON.stringify({type:"turn.state",...base,generation:9,revision:20,state:"error"})},browserGeneration,current);
 assert(node.querySelector(".turn-status").textContent==="완료 · 개발용 절차"&&!node.querySelector(".error").textContent,"terminal or stale identity revived card");
 const visible=node.querySelector(".turn-status").textContent+node.querySelector(".error").textContent;for(const forbidden of ["prompt","reasoning","tool arguments","Traceback"])assert(!visible.includes(forbidden),"hidden internals exposed");
})().catch(error=>{console.error(error);process.exit(1)});
"""
        result=run_node_harness(harness)
        self.assertEqual(result.returncode,0,result.stderr)

    def test_audio_worklet_accumulates_twenty_ms_transferable_blocks(self):
        worklet=(
            ROOT/"src"/"voice_workflow_agent"/"static"/"mic-capture-worklet.js"
        ).read_text(encoding="utf-8")
        harness=r"""
const assert=(ok,message)=>{if(!ok)throw new Error(message)};
let Processor=null,posted=[];
globalThis.sampleRate=48000;
globalThis.AudioWorkletProcessor=class{constructor(){this.port={onmessage:null,postMessage:(value,transfer)=>posted.push({value,transfer})}}};
globalThis.registerProcessor=(name,value)=>{assert(name==="voice-workflow-mic-capture","processor name");Processor=value};
""" + worklet + r"""
const processor=new Processor(),block=new Float32Array(128);block.fill(.25);
for(let i=0;i<8;i++)assert(processor.process([ [block] ]),"processor stopped early");
assert(posted.length===1,"128-sample blocks were not accumulated");
assert(posted[0].value instanceof ArrayBuffer&&posted[0].value.byteLength===960*4,"batch is not 20 ms Float32");
assert(posted[0].transfer.length===1&&posted[0].transfer[0]===posted[0].value,"batch was not transferred");
processor.port.onmessage({data:{type:"stop"}});
assert(processor.process([ [block] ])===false,"stopped processor remained active");
"""
        result=run_node_harness(harness)
        self.assertEqual(result.returncode,0,result.stderr)

    def test_protocol_visual_and_filler_use_production_handlers(self):
        html=(
            ROOT/"src"/"voice_workflow_agent"/"static"/"index.html"
        ).read_text(encoding="utf-8")
        script=html.split("<script>",1)[1].split("</script>",1)[0]
        harness=r"""
const assert=(ok,message)=>{if(!ok)throw new Error(message)};
class Element{constructor(){this.children=[];this.fields={};this.textContent="";this.disabled=false;this.hidden=false;this.removed=false;this.dataset={};this.options=[];this.attributes={}}set innerHTML(v){for(const c of ["transcript","reply","turn-status","filler-status","server-operation","tools","turn-visual","stats","error"]){const item=new Element();item.textContent=c==="transcript"?"듣는 중…":"";this.fields[c]=item}}querySelector(s){return this.fields[s.slice(1)]}prepend(n){this.children.unshift(n)}replaceChildren(){this.children=[];this.options=this.children}appendChild(n){this.children.push(n);this.options=this.children}remove(){this.removed=true}addEventListener(kind,fn){this["on"+kind]=fn}setAttribute(name,value){this.attributes[name]=value}}
const names=["start","stop","log","status","state","last-report-id","last-report-state","pending-report","language-status","language-mode","manual-language","pipeline-mode","protocol-id","protocol-pdf","register-protocol","protocol-upload-status","protocol-analysis-progress","protocol-readiness","protocol-revision","session-configuration-status","new-user","language-confirmation","procedure-title","procedure-meta","procedure-status","procedure-progress","procedure-step-title","procedure-primary","procedure-instruction","procedure-warning","procedure-spoken-summary","repeat-step","next-step","voice-command-hint","procedure-visual","source-visual-state","source-filename","source-page-number","source-short-hash","voice-processing","voice-filler-status","voice-primary-status","procedure-source","procedure-timer","procedure-observation","procedure-handoff","procedure-audit"];
const ids=Object.fromEntries(names.map(x=>{const element=new Element();element.id=x;return[x,element]}));ids["language-mode"].value="manual";ids["manual-language"].value="ko";ids["pipeline-mode"].value="cascade";ids["protocol-id"].value="protocol-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";for(const stage of ["recognized","routed","protocol","prepared","audio"]){const item=new Element();item.dataset.stage=stage;ids["voice-processing"].appendChild(item);}
globalThis.document={getElementById:id=>ids[id],createElement:()=>new Element(),querySelector:()=>null};globalThis.location={protocol:"http:",host:"test"};globalThis.addEventListener=()=>{};
class WS{static OPEN=1;static CLOSING=2;constructor(){this.readyState=1;this.sent=[]}send(v){this.sent.push(v)}close(){this.readyState=3}}
globalThis.WebSocket=WS;Object.defineProperty(globalThis,"navigator",{value:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[]})}},configurable:true});globalThis.AudioContext=class{};
"""+script+r"""
(async()=>{const current=socket,browserGeneration=sessionGeneration,protocol_id="protocol-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",revision_id="pdf-1-analysis-1",configuration_id=71;acceptedSessionConfiguration={configuration_id,mode:"cascade",language:"ko",protocol_id,revision_id};sessionActive=true;pipelineMode="cascade";
let fillerStopped=0;playContext={state:"running",destination:{},resume:async()=>{},createBuffer:()=>({getChannelData:()=>new Float32Array(320)}),createBufferSource:()=>({onended:null,connect(){},start(){},stop(){fillerStopped++},disconnect(){}})};
await onMessage({data:JSON.stringify({type:"speech.start",turn_id:1,generation:5})},browserGeneration,current);
const visual={asset_id:"source-crop-1-1",protocol_id,revision_id,kind:"source_crop",source_document_id:"b".repeat(64),source_page:1,mime_type:"image/png",sha256:"b".repeat(64),alt_text:"Step 1 verified source crop",label:"원본 시각 자료 · PDF p.1",caption_primary:"용액을 추가합니다.",caption_source:"1. Add solution.",source_page_url:`/api/protocols/${protocol_id}/revisions/${revision_id}/source-pages/1`,normalized_bounding_box:[0,0,1,1],url:`/api/protocols/${protocol_id}/revisions/${revision_id}/assets/source-crop-1-1`};
const state={attached:true,protocol_id,revision_id,display_name:"Protocol Alpha",development_only:false,readiness_status:"guidance_ready",active:true,current_step_label:"1",current_step_id:"step-1",total_steps:1,at_final_step:true,block_reason:null,revision:1,primary_summary:"용액을 추가합니다.",display_summary:"1. Add solution.",spoken_summary:"1단계입니다.",source_filename:"alpha.pdf",source_sha256:"b".repeat(64),source_page_refs:[1],visual_assets:[visual],visual_status:"available",warning_texts:["Keep safe."],critical_warning_texts:[]};
await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id,turn_id:1,generation:5,state,action:"current"})},browserGeneration,current);assert(ids["procedure-primary"].textContent.includes("용액을 추가합니다.")&&ids["procedure-instruction"].textContent.includes("1. Add solution.")&&ids["procedure-warning"].textContent.includes("Keep safe.")&&!ids["procedure-warning"].hidden,"bilingual instruction or warning not independently readable");assert(ids["procedure-spoken-summary"].textContent==="1단계입니다."&&ids["source-filename"].textContent==="alpha.pdf"&&ids["source-page-number"].textContent==="p.1"&&ids["source-short-hash"].textContent.startsWith("bbbbbbbbbbbb"),"source or speech metadata missing");assert(ids["procedure-visual"].children.length===5&&ids["procedure-visual"].children[1].src===visual.url&&ids["procedure-visual"].children[4].href===visual.source_page_url&&ids["procedure-visual"].children[4].rel==="noopener"&&ids["source-visual-state"].textContent.includes("불러오는 중"),"current visual loading state missing");ids["procedure-visual"].children[1].onload();assert(ids["source-visual-state"].textContent==="원본 시각 자료 · PDF p.1","current visual ready state missing");const turnVisual=turnNode(1,browserGeneration).querySelector(".turn-visual");assert(turnVisual.children.length===1&&turnVisual.children[0].textContent.includes("Visual 패널"),"compact Turn visual outcome missing");
const stale={...state,revision:0,current_step_label:"9",visual_assets:[]};await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id,turn_id:1,generation:5,state:stale,action:"next"})},browserGeneration,current);assert(curatedProtocolState.current_step_label==="1"&&turnVisual.children.length===1,"stale visual replaced current state");
const wrongAsset={...visual,protocol_id:"protocol-cccccccccccccccccccccccccccccccc"},wrongState={...state,revision:2,visual_assets:[wrongAsset]};await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id,turn_id:2,generation:6,state:wrongState,action:"current"})},browserGeneration,current);assert(ids["procedure-visual"].children.length===1,`mismatched visual was trusted: ${ids["procedure-visual"].children.length}`);assert(ids["source-visual-state"].textContent.includes("검증 실패"),`visual failure state missing: ${ids["source-visual-state"].textContent}`);assert(ids["procedure-instruction"].textContent.includes("1. Add solution."),`instruction fallback disappeared: ${ids["procedure-instruction"].textContent}`);assert(ids["procedure-warning"].textContent.includes("Keep safe."),`warning fallback disappeared: ${ids["procedure-warning"].textContent}`);assert(turnVisual.children.length===1,"historical visual changed with current state");
const wrongHashAsset={...visual,sha256:"c".repeat(64),source_document_id:"c".repeat(64)},wrongHashState={...state,revision:3,visual_assets:[wrongHashAsset]};await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id,turn_id:3,generation:7,state:wrongHashState,action:"current"})},browserGeneration,current);assert(ids["procedure-visual"].children.length===1&&ids["source-visual-state"].textContent.includes("검증 실패"),"visual with wrong source identity was trusted");
const unavailableState={...state,revision:4,visual_assets:[],visual_status:"unavailable"};await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id,turn_id:4,generation:8,state:unavailableState,action:"current"})},browserGeneration,current);assert(ids["source-visual-state"].textContent.includes("사용 가능한 시각 자료 없음")&&ids["procedure-instruction"].textContent.includes("1. Add solution."),"text-only visual fallback missing");const failedLoadState={...state,revision:5};await onMessage({data:JSON.stringify({type:"protocol.fixture.state",configuration_id,turn_id:5,generation:9,state:failedLoadState,action:"current"})},browserGeneration,current);ids["procedure-visual"].children[1].onerror();assert(ids["source-visual-state"].textContent.includes("시각 자료 불러오기 실패")&&ids["procedure-instruction"].textContent.includes("1. Add solution."),"visual load failure removed instruction");assert(turnVisual.children.length===1,"historical visual changed after fallback states");
const turnState={type:"turn.state",configuration_id,turn_id:1,generation:5};await onMessage({data:JSON.stringify({...turnState,revision:1,state:"routing",route:"curated_protocol"})},browserGeneration,current);await onMessage({data:JSON.stringify({...turnState,revision:2,state:"checking_protocol",route:"curated_protocol"})},browserGeneration,current);await onMessage({data:JSON.stringify({...turnState,revision:3,state:"synthesizing",route:"curated_protocol"})},browserGeneration,current);await onMessage({data:JSON.stringify({...turnState,revision:4,state:"playing",route:"curated_protocol"})},browserGeneration,current);assert(turnNode(1,browserGeneration).querySelector(".turn-status").textContent.includes("재생 중"),"Turn-owned playing state missing");
assert(normalizePresentationText("1mm3 AMBIC 001500 500 µL 37°C")==="1 mm³ (AMBIC) 00:15:00 500 µL 37°C","derived presentation glyph normalization failed");
await onMessage({data:JSON.stringify({type:"filler.audio.start",configuration_id,turn_id:1,generation:5,frame_count:1,sample_rate:16000,encoding:"pcm_s16le"})},browserGeneration,current);await onMessage({data:new ArrayBuffer(640)},browserGeneration,current);await onMessage({data:JSON.stringify({type:"filler.audio.end",configuration_id,turn_id:1,generation:5,frame_count:1})},browserGeneration,current);assert(fillerSource!==null,"eligible filler did not enter the playback scheduler");await onMessage({data:JSON.stringify({type:"audio.segment.start",turn_id:1,generation:5,segment_index:0,frame_count:1})},browserGeneration,current);assert(fillerStopped===1&&fillerSource===null&&receiving.segment_index===0,"primary did not atomically stop filler");
const fillerCard=turnNode(1,browserGeneration);await onMessage({data:JSON.stringify({type:"turn.filler",configuration_id,turn_id:1,generation:5,outcome:"scheduled"})},browserGeneration,current);assert(fillerCard.querySelector(".filler-status").textContent==="","scheduled filler created visible history");await onMessage({data:JSON.stringify({type:"turn.filler",configuration_id,turn_id:1,generation:5,outcome:"played"})},browserGeneration,current);assert(fillerCard.querySelector(".filler-status").textContent==="","filler outcome attached before transcript acceptance");await onMessage({data:JSON.stringify({type:"transcript",configuration_id,turn_id:1,generation:5,text:"현재 단계 알려줘"})},browserGeneration,current);assert(fillerCard.querySelector(".filler-status").textContent==="대기 안내 · 재생됨","played filler did not attach to the matching accepted Turn");await onMessage({data:JSON.stringify({type:"turn.filler",configuration_id,turn_id:1,generation:5,outcome:"skipped"})},browserGeneration,current);assert(fillerCard.querySelector(".filler-status").textContent==="","skipped filler left visible history");await onMessage({data:JSON.stringify({type:"turn.filler",configuration_id,turn_id:1,generation:5,outcome:"cancelled"})},browserGeneration,current);assert(fillerCard.querySelector(".filler-status").textContent==="","cancelled filler left visible history");
const catalogEntries=[
 {protocol_id:"candidate-a-curated-development-v1",title:"Candidate A",revision_id:"fixture-c2779c24924dbeb3c83d",readiness_status:"analysis_required",approval_status:"development_only_not_final_acceptance",analysis_status:"validated_curated_fixture",available_for_execution:true,development_only:true},
 {protocol_id:"protocol-1",title:"Ready",revision_id:"pdf-1-analysis-1",readiness_status:"guidance_ready",analysis_status:"validated",available_for_execution:true},
 {protocol_id:"protocol-2",title:"Review",revision_id:"pdf-1",readiness_status:"analysis_required",analysis_status:"structured_analysis_ready",available_for_execution:false},
 {protocol_id:"protocol-3",title:"OCR",revision_id:"pdf-1",readiness_status:"analysis_required",analysis_status:"ocr_required",available_for_execution:false},
 {protocol_id:"protocol-4",title:"Failed",revision_id:"pdf-1",readiness_status:"analysis_required",analysis_status:"analysis_failed",available_for_execution:false},
 {protocol_id:"protocol-5",title:"Large",revision_id:"pdf-1",readiness_status:"analysis_required",analysis_status:"chunk_analysis_in_progress",available_for_execution:false,analysis_run:{state:"chunk_analysis_in_progress",total_chunks:3,completed_chunks:1,failed_chunks:0,pending_chunks:2,chunks:[{source_page_start:1,source_page_end:2,status:"completed"},{source_page_start:3,source_page_end:4,status:"in_progress"},{source_page_start:5,source_page_end:6,status:"pending"}]}}
];
fetch=async()=>{assert(ids["protocol-readiness"].textContent.includes("불러오는 중"),"catalog loading state missing");return{ok:true,json:async()=>({protocols:catalogEntries})}};ids["protocol-id"].value="unavailable-old-selection";await loadProtocolCatalog();assert(protocolCatalog.size===6,`catalog size: ${protocolCatalog.size}`);assert([...protocolCatalog.values()].filter(item=>item.protocol_id==="candidate-a-curated-development-v1").length===1,"Candidate A did not appear exactly once after catalog reload");assert(protocolCatalog.get("candidate-a-curated-development-v1").development_only===true&&protocolCatalog.get("candidate-a-curated-development-v1").approval_status==="development_only_not_final_acceptance","Candidate A lost development-only status");assert(ids["protocol-id"].value==="candidate-a-curated-development-v1",`ready selection missing: ${ids["protocol-id"].value}; options=${ids["protocol-id"].options.map(option=>`${option.value}/${option.disabled}`).join(",")}`);assert(ids["protocol-readiness"].textContent.includes("개발용"),`development status missing: ${ids["protocol-readiness"].textContent}`);ids["protocol-id"].value="protocol-5";renderSelectedProtocolContext();assert(ids["protocol-analysis-progress"].textContent.includes("전체 3 / 완료 1 / 실패 0 / 대기 2")&&ids["protocol-analysis-progress"].textContent.includes("p.3-4 in_progress")&&ids["protocol-analysis-progress"].textContent.includes("검토·승인 전 실행 불가"),`chunk progress missing: ${ids["protocol-analysis-progress"].textContent}`);for(const [id,label] of [["protocol-2","구조화 분석"],["protocol-3","OCR 필요"],["protocol-4","분석 실패"],["protocol-5","대형 문서 분석 진행 중"]]){ids["protocol-id"].value=id;renderSelectedProtocolContext();assert(ids["protocol-readiness"].textContent.includes(label),`catalog state missing: ${id}`);}renderState("LISTENING");assert(ids["protocol-id"].disabled&&ids["protocol-id"].attributes["aria-disabled"]==="true","active session did not accessibly lock selector");fetch=async()=>({ok:false,json:async()=>({})});await loadProtocolCatalog();assert(ids["protocol-readiness"].textContent.includes("불러오기 실패")&&ids["protocol-id"].children.length===1&&ids["protocol-analysis-progress"].textContent.includes("상태 없음"),"catalog failure state missing");
const selectedPdf={name:"selected.pdf",type:"application/pdf"};ids["protocol-pdf"].files=[selectedPdf];ids["register-protocol"].disabled=false;const unchangedProgress=ids["protocol-analysis-progress"].textContent;
const errorCases=[
 ["invalid_pdf","PDF 파일이 손상되었거나 다운로드가 완료되지 않았습니다. 원본 파일을 다시 내려받아 선택해 주세요."],
 ["protocol_pdf_too_large","PDF 파일 크기가 등록 한도를 초과했습니다. 더 작은 파일을 선택해 주세요."],
 ["protocol_catalog_unavailable","프로토콜 등록 기능을 사용할 수 없습니다. 서버 관리자에게 문의해 주세요."],
 ["unsupported_pdf_media_type","PDF 파일만 등록할 수 있습니다."]
];
for(const [code,message] of errorCases){let calls=0;fetch=async(url,options)=>{calls++;assert(url.includes("filename=selected.pdf")&&options.method==="POST"&&options.headers["Content-Type"]==="application/pdf"&&options.body===selectedPdf&&options.redirect==="error","production raw upload contract changed");return{ok:false,headers:{get:()=>"application/json"},json:async()=>({detail:code})}};await registerSelectedProtocol();assert(calls===1,`failed ${code} refreshed catalog`);assert(ids["protocol-upload-status"].textContent===message,`safe upload message missing for ${code}`);assert(!ids["register-protocol"].disabled&&ids["protocol-pdf"].files[0]===selectedPdf,"recoverable failure lost selection or disabled button");assert(ids["protocol-analysis-progress"].textContent===unchangedProgress,"failed registration displayed analysis progress");}
let nonJsonCalls=0;fetch=async()=>{nonJsonCalls++;return{ok:false,headers:{get:()=>"text/html"},json:async()=>{throw new Error("must not parse HTML")}}};await registerSelectedProtocol();assert(nonJsonCalls===1&&ids["protocol-upload-status"].textContent==="PDF 등록 중 서버 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.","non-JSON upload failure was not sanitized");assert(!ids["register-protocol"].disabled,"non-JSON failure left button disabled");
fetch=async()=>{throw new TypeError("offline")};await registerSelectedProtocol();assert(ids["protocol-upload-status"].textContent==="서버에 연결할 수 없습니다. 네트워크 상태를 확인해 주세요."&&!ids["register-protocol"].disabled,"network upload failure was not distinguished");
ids["register-protocol"].disabled=true;let duplicateCalls=0;fetch=async()=>{duplicateCalls++;throw new Error("duplicate")};await registerSelectedProtocol();assert(duplicateCalls===0,"disabled upload button allowed a duplicate request");ids["register-protocol"].disabled=false;
let successCalls=0;fetch=async()=>{successCalls++;if(successCalls===1)return{ok:true,headers:{get:()=>"application/json"},json:async()=>({deduplicated:false,protocol:{protocol_id:"protocol-new"}})};return{ok:true,json:async()=>({protocols:catalogEntries})}};await registerSelectedProtocol();assert(successCalls===2,"successful registration did not refresh catalog exactly once");assert(!ids["register-protocol"].disabled,"successful registration left button disabled");
})().catch(error=>{console.error(error);process.exit(1)});
"""
        result=run_node_harness(harness)
        self.assertEqual(result.returncode,0,result.stderr)

    def test_protocol_workspace_is_responsive_and_accessible(self):
        html=(
            ROOT/"src"/"voice_workflow_agent"/"static"/"index.html"
        ).read_text(encoding="utf-8")
        self.assertIn(
            'grid-template-areas:"setup setup" "work chat"',
            html,
        )
        self.assertIn(
            'grid-template-areas:"setup" "work" "chat"', html
        )
        self.assertNotIn('class="panel processing-card"', html)
        self.assertNotIn('id="voice-processing"', html)
        self.assertIn('align-items:start', html)
        self.assertIn('position:sticky', html)
        self.assertIn('top:4.5rem', html)
        self.assertIn('calc(100vh - 5.5rem)', html)
        self.assertIn('min-height:24rem', html)
        self.assertIn('class="turn-diagnostics"', html)
        self.assertIn('summary>근거·처리·지연시간 세부정보', html)
        self.assertLess(
            html.index('class="panel timeline"'),
            html.index('class="example-strip"'),
        )
        self.assertLess(html.index('class="panel voice-panel"'), html.index('class="workflow-grid"'))
        self.assertLess(html.index('class="workflow-grid"'), html.index('class="panel timeline"'))
        self.assertLess(
            html.index('class="report-card procedure-report"'),
            html.index('class="panel timeline"'),
        )
        self.assertEqual(html.count('id="experiment-report-title"'), 1)
        self.assertNotIn('grid-area:report', html)
        self.assertIn("기록 보기 · 이상 사항 · 내보내기", html)
        self.assertIn("function applyBrainState", html)
        self.assertIn("function applyBrainAnswerEnrichment", html)
        self.assertIn('m.type==="session.greeting"', html)
        self.assertIn('message.status==="background_bounded"', html)
        self.assertNotIn('--procedure-workspace-height', html)
        self.assertIn('overflow-y:auto', html)
        self.assertNotIn('function syncConversationHeight', html)
        self.assertIn('function updateWorkflowTimer', html)
        self.assertIn('실험 진행 경과 시간', html)
        self.assertIn('<summary>개발 상세 정보</summary>', html)
        self.assertNotIn('<summary>개발자 상세 정보</summary>', html)
        self.assertIn('function sanitizeExternalResearchAnswer', html)
        self.assertNotIn('id="language-mode"', html)
        self.assertNotIn('id="manual-language"', html)
        self.assertIn('class="btn-register"', html)
        self.assertIn('class="btn-file-select"', html)
        self.assertIn('class="report-event-ledger"', html)
        self.assertNotIn("overflow-x:scroll", html)
        self.assertNotIn("generated_schematic", html)
        self.assertNotIn("diagram-step-", html)
        self.assertNotIn("검증된 도식", html)
        self.assertNotIn("답변 다시 듣기", html)

    def test_audio_worklet_module_is_in_the_fastapi_static_mount(self):
        from voice_workflow_agent.server import app

        static_mount=next(
            route for route in app.routes
            if getattr(route,"name",None)=="static")
        path,stat_result=static_mount.app.lookup_path(
            "mic-capture-worklet.js")
        self.assertTrue(Path(path).is_file())
        self.assertIsNotNone(stat_result)

if __name__ == "__main__": unittest.main()
