"""Old setting names and the names that replaced them (decision of 2026-10-04).

Every setting the code reads now carries the ``VOINEY_LAB_`` prefix: an old
prefixed name keeps the rest of its name under the new prefix, and an old
unprefixed application setting gains the prefix in front. Names other software
defines (``XAI_API_KEY`` and the like) were never renamed; ``setting_names``
lists them.

This module is the one place in the repository that spells an old setting
name. Two things read it: the start-up guard in ``setting_names``, which
refuses to start while an old name is set, and ``scripts/migrate_env.py``,
which renames them in a ``.env``. There is no transition period in which the
code reads an old name.
"""

from __future__ import annotations

OLD_PREFIX = "VOICE_WORKFLOW_AGENT_"
NEW_PREFIX = "VOINEY_LAB_"

#: Old name -> new name, for every setting the code read before the rename.
RENAMED: dict[str, str] = {
    # VOICE_WORKFLOW_AGENT_X -> VOINEY_LAB_X (80)
    "VOICE_WORKFLOW_AGENT_ADMIN_TOKEN": "VOINEY_LAB_ADMIN_TOKEN",
    "VOICE_WORKFLOW_AGENT_ALLOWED_LANGUAGES": "VOINEY_LAB_ALLOWED_LANGUAGES",
    "VOICE_WORKFLOW_AGENT_ANALYTICS_RETENTION_DAYS": "VOINEY_LAB_ANALYTICS_RETENTION_DAYS",
    "VOICE_WORKFLOW_AGENT_ANSWER_BRAIN_ENABLED": "VOINEY_LAB_ANSWER_BRAIN_ENABLED",
    "VOICE_WORKFLOW_AGENT_ANSWER_BRAIN_MODEL": "VOINEY_LAB_ANSWER_MODEL",
    "VOICE_WORKFLOW_AGENT_ANSWER_BRAIN_PRIMARY_BUDGET_SECONDS": "VOINEY_LAB_ANSWER_BRAIN_PRIMARY_BUDGET_SECONDS",
    "VOICE_WORKFLOW_AGENT_ANSWER_BRAIN_TIMEOUT_SECONDS": "VOINEY_LAB_ANSWER_BRAIN_TIMEOUT_SECONDS",
    "VOICE_WORKFLOW_AGENT_CHUNK_CACHE_DIR": "VOINEY_LAB_CHUNK_CACHE_DIR",
    "VOICE_WORKFLOW_AGENT_CLOVA_OCR_INVOKE_URL": "VOINEY_LAB_CLOVA_OCR_INVOKE_URL",
    "VOICE_WORKFLOW_AGENT_CLOVA_OCR_SECRET": "VOINEY_LAB_CLOVA_OCR_SECRET",
    "VOICE_WORKFLOW_AGENT_CURATED_PROTOCOL_FIXTURE": "VOINEY_LAB_CURATED_PROTOCOL_FIXTURE",
    "VOICE_WORKFLOW_AGENT_CURATED_PROTOCOL_PROVENANCE": "VOINEY_LAB_CURATED_PROTOCOL_PROVENANCE",
    "VOICE_WORKFLOW_AGENT_CURATED_PROTOCOL_SOURCE_PDF": "VOINEY_LAB_CURATED_PROTOCOL_SOURCE_PDF",
    "VOICE_WORKFLOW_AGENT_DEV_AUTH_PROFILES": "VOINEY_LAB_DEV_AUTH_PROFILES",
    "VOICE_WORKFLOW_AGENT_EXPERIMENT_REPORTS_DATABASE": "VOINEY_LAB_EXPERIMENT_REPORTS_DATABASE",
    "VOICE_WORKFLOW_AGENT_EXPERIMENT_REPORTS_ENABLED": "VOINEY_LAB_EXPERIMENT_REPORTS_ENABLED",
    "VOICE_WORKFLOW_AGENT_EXPERIMENT_REPORT_DB": "VOINEY_LAB_EXPERIMENT_REPORT_DB",
    "VOICE_WORKFLOW_AGENT_EXTERNAL_REFERENCES_ENABLED": "VOINEY_LAB_EXTERNAL_REFERENCES_ENABLED",
    "VOICE_WORKFLOW_AGENT_EXTERNAL_REFERENCE_DOMAINS": "VOINEY_LAB_EXTERNAL_REFERENCE_DOMAINS",
    "VOICE_WORKFLOW_AGENT_EXTERNAL_REFERENCE_MODEL": "VOINEY_LAB_SUPPLEMENTAL_MODEL",
    "VOICE_WORKFLOW_AGENT_EXTERNAL_REFERENCE_TIMEOUT_SECONDS": "VOINEY_LAB_EXTERNAL_REFERENCE_TIMEOUT_SECONDS",
    "VOICE_WORKFLOW_AGENT_FACILITY_ID": "VOINEY_LAB_FACILITY_ID",
    "VOICE_WORKFLOW_AGENT_FROM_EMAIL": "VOINEY_LAB_FROM_EMAIL",
    "VOICE_WORKFLOW_AGENT_GENERATED_VISUALS_ENABLED": "VOINEY_LAB_GENERATED_VISUALS_ENABLED",
    "VOICE_WORKFLOW_AGENT_GENERATED_VISUAL_MODEL": "VOINEY_LAB_GENERATED_VISUAL_MODEL",
    "VOICE_WORKFLOW_AGENT_GENERATED_VISUAL_TIMEOUT_SECONDS": "VOINEY_LAB_GENERATED_VISUAL_TIMEOUT_SECONDS",
    "VOICE_WORKFLOW_AGENT_GOOGLE_VISION_API_KEY": "VOINEY_LAB_GOOGLE_VISION_API_KEY",
    "VOICE_WORKFLOW_AGENT_LLM_ROUTER_ENABLED": "VOINEY_LAB_LLM_ROUTER_ENABLED",
    "VOICE_WORKFLOW_AGENT_LLM_ROUTER_MODEL": "VOINEY_LAB_ROUTER_MODEL",
    "VOICE_WORKFLOW_AGENT_LLM_ROUTER_TIMEOUT_SECONDS": "VOINEY_LAB_LLM_ROUTER_TIMEOUT_SECONDS",
    "VOICE_WORKFLOW_AGENT_MOSS_ALLOWED_SCOPES": "VOINEY_LAB_MOSS_ALLOWED_SCOPES",
    "VOICE_WORKFLOW_AGENT_MOSS_ALPHA": "VOINEY_LAB_MOSS_ALPHA",
    "VOICE_WORKFLOW_AGENT_MOSS_AUTO_REFRESH": "VOINEY_LAB_MOSS_AUTO_REFRESH",
    "VOICE_WORKFLOW_AGENT_MOSS_CANDIDATE_LIMIT": "VOINEY_LAB_MOSS_CANDIDATE_LIMIT",
    "VOICE_WORKFLOW_AGENT_MOSS_ENABLED": "VOINEY_LAB_MOSS_ENABLED",
    "VOICE_WORKFLOW_AGENT_MOSS_LOAD_TIMEOUT_SECONDS": "VOINEY_LAB_MOSS_LOAD_TIMEOUT_SECONDS",
    "VOICE_WORKFLOW_AGENT_MOSS_QUERY_TIMEOUT_MS": "VOINEY_LAB_MOSS_QUERY_TIMEOUT_MS",
    "VOICE_WORKFLOW_AGENT_MOSS_REFRESH_SECONDS": "VOINEY_LAB_MOSS_REFRESH_SECONDS",
    "VOICE_WORKFLOW_AGENT_MULTI_BRAIN_ENABLED": "VOINEY_LAB_MULTI_BRAIN_ENABLED",
    "VOICE_WORKFLOW_AGENT_MULTI_BRAIN_MODEL": "VOINEY_LAB_ANSWER_MODEL",
    "VOICE_WORKFLOW_AGENT_OCR_PROVIDERS": "VOINEY_LAB_OCR_PROVIDERS",
    "VOICE_WORKFLOW_AGENT_OIDC_AUDIENCE": "VOINEY_LAB_OIDC_AUDIENCE",
    "VOICE_WORKFLOW_AGENT_OIDC_ISSUER": "VOINEY_LAB_OIDC_ISSUER",
    "VOICE_WORKFLOW_AGENT_OIDC_JWKS_URL": "VOINEY_LAB_OIDC_JWKS_URL",
    "VOICE_WORKFLOW_AGENT_OIDC_NAME_CLAIM": "VOINEY_LAB_OIDC_NAME_CLAIM",
    "VOICE_WORKFLOW_AGENT_OIDC_ROLES_CLAIM": "VOINEY_LAB_OIDC_ROLES_CLAIM",
    "VOICE_WORKFLOW_AGENT_OIDC_TENANT_CLAIM": "VOINEY_LAB_OIDC_TENANT_CLAIM",
    "VOICE_WORKFLOW_AGENT_PDF_WORKER_TIMEOUT_SECONDS": "VOINEY_LAB_PDF_WORKER_TIMEOUT_SECONDS",
    "VOICE_WORKFLOW_AGENT_PLANNER_BRAIN_TIMEOUT_SECONDS": "VOINEY_LAB_PLANNER_BRAIN_TIMEOUT_SECONDS",
    "VOICE_WORKFLOW_AGENT_PROCEDURE_CATALOG": "VOINEY_LAB_PROCEDURE_CATALOG",
    "VOICE_WORKFLOW_AGENT_PROCEDURE_STORE": "VOINEY_LAB_PROCEDURE_STORE",
    "VOICE_WORKFLOW_AGENT_PROTOCOL_CLAIM_CHUNKS_ENABLED": "VOINEY_LAB_PROTOCOL_CLAIM_CHUNKS_ENABLED",
    "VOICE_WORKFLOW_AGENT_PROTOCOL_DATA_DIR": "VOINEY_LAB_PROTOCOL_DATA_DIR",
    "VOICE_WORKFLOW_AGENT_PROTOCOL_ENABLED": "VOINEY_LAB_PROTOCOL_ENABLED",
    "VOICE_WORKFLOW_AGENT_REPORT_WRITER_ENABLED": "VOINEY_LAB_REPORT_WRITER_ENABLED",
    "VOICE_WORKFLOW_AGENT_REPORT_WRITER_MODEL": "VOINEY_LAB_REPORT_MODEL",
    "VOICE_WORKFLOW_AGENT_REPORT_WRITER_TIMEOUT_SECONDS": "VOINEY_LAB_REPORT_WRITER_TIMEOUT_SECONDS",
    "VOICE_WORKFLOW_AGENT_SAFETY_CATALOG": "VOINEY_LAB_SAFETY_CATALOG",
    "VOICE_WORKFLOW_AGENT_SAFETY_USAGE_SCOPE": "VOINEY_LAB_SAFETY_USAGE_SCOPE",
    "VOICE_WORKFLOW_AGENT_SEMANTIC_INTENT_ENABLED": "VOINEY_LAB_SEMANTIC_INTENT_ENABLED",
    "VOICE_WORKFLOW_AGENT_SEMANTIC_INTENT_MIN_CONFIDENCE": "VOINEY_LAB_SEMANTIC_INTENT_MIN_CONFIDENCE",
    "VOICE_WORKFLOW_AGENT_SEMANTIC_INTENT_MODEL": "VOINEY_LAB_SEMANTIC_INTENT_MODEL",
    "VOICE_WORKFLOW_AGENT_SEMANTIC_INTENT_MUTATION_MIN_CONFIDENCE": "VOINEY_LAB_SEMANTIC_INTENT_MUTATION_MIN_CONFIDENCE",
    "VOICE_WORKFLOW_AGENT_SEMANTIC_INTENT_TIMEOUT_SECONDS": "VOINEY_LAB_SEMANTIC_INTENT_TIMEOUT_SECONDS",
    "VOICE_WORKFLOW_AGENT_SESSION_LANGUAGE": "VOINEY_LAB_SESSION_LANGUAGE",
    "VOICE_WORKFLOW_AGENT_SOURCE_BRAIN_ENABLED": "VOINEY_LAB_SOURCE_BRAIN_ENABLED",
    "VOICE_WORKFLOW_AGENT_SOURCE_BRAIN_MODEL": "VOINEY_LAB_ANSWER_MODEL",
    "VOICE_WORKFLOW_AGENT_STT_DIAGNOSTICS_ENABLED": "VOINEY_LAB_STT_DIAGNOSTICS_ENABLED",
    "VOICE_WORKFLOW_AGENT_STT_DIAGNOSTIC_DIR": "VOINEY_LAB_STT_DIAGNOSTIC_DIR",
    "VOICE_WORKFLOW_AGENT_STT_DIAGNOSTIC_MAX_FILES": "VOINEY_LAB_STT_DIAGNOSTIC_MAX_FILES",
    "VOICE_WORKFLOW_AGENT_USAGE_SCOPE": "VOINEY_LAB_USAGE_SCOPE",
    "VOICE_WORKFLOW_AGENT_VISUAL_BRAIN_ENABLED": "VOINEY_LAB_VISUAL_BRAIN_ENABLED",
    "VOICE_WORKFLOW_AGENT_VISUAL_BRAIN_MODEL": "VOINEY_LAB_ANSWER_MODEL",
    "VOICE_WORKFLOW_AGENT_WEB_VISUAL_TIMEOUT_SECONDS": "VOINEY_LAB_WEB_VISUAL_TIMEOUT_SECONDS",
    "VOICE_WORKFLOW_AGENT_WORKSPACE_DATA_DIR": "VOINEY_LAB_WORKSPACE_DATA_DIR",
    "VOICE_WORKFLOW_AGENT_WORKSPACE_ENABLED": "VOINEY_LAB_WORKSPACE_ENABLED",
    # Y -> VOINEY_LAB_Y (50; the 7 mail settings the code no longer reads
    # were taken out by lane M1, decision 5b)
    "CANDIDATE_A_SOURCE_PDF": "VOINEY_LAB_CANDIDATE_A_SOURCE_PDF",
    "CASCADE_BARGE_IN_PREFIX_MS": "VOINEY_LAB_CASCADE_BARGE_IN_PREFIX_MS",
    "CASCADE_FILLER_DELAY_MS": "VOINEY_LAB_CASCADE_FILLER_DELAY_MS",
    "CASCADE_FILLER_MODE": "VOINEY_LAB_CASCADE_FILLER_MODE",
    "CASCADE_FILLER_STATUS_DELAY_MS": "VOINEY_LAB_CASCADE_FILLER_STATUS_DELAY_MS",
    "CASCADE_VAD_COOLDOWN_MS": "VOINEY_LAB_CASCADE_VAD_COOLDOWN_MS",
    "CASCADE_VAD_ENDPOINT_SILENCE_MS": "VOINEY_LAB_CASCADE_VAD_ENDPOINT_SILENCE_MS",
    "CASCADE_VAD_LISTENING_ONSET_VOICED_FRAMES": "VOINEY_LAB_CASCADE_VAD_LISTENING_ONSET_VOICED_FRAMES",
    "CASCADE_VAD_LISTENING_ONSET_WINDOW_FRAMES": "VOINEY_LAB_CASCADE_VAD_LISTENING_ONSET_WINDOW_FRAMES",
    "CASCADE_VAD_LISTENING_RESUME_VOICED_FRAMES": "VOINEY_LAB_CASCADE_VAD_LISTENING_RESUME_VOICED_FRAMES",
    "CASCADE_VAD_LISTENING_RESUME_WINDOW_FRAMES": "VOINEY_LAB_CASCADE_VAD_LISTENING_RESUME_WINDOW_FRAMES",
    "CASCADE_VAD_MAX_UTTERANCE_MS": "VOINEY_LAB_CASCADE_VAD_MAX_UTTERANCE_MS",
    "CASCADE_VAD_MIN_SPEECH_MS": "VOINEY_LAB_CASCADE_VAD_MIN_SPEECH_MS",
    "CASCADE_VAD_MODE": "VOINEY_LAB_CASCADE_VAD_MODE",
    "CASCADE_VAD_ONSET_VOICED_FRAMES": "VOINEY_LAB_CASCADE_VAD_ONSET_VOICED_FRAMES",
    "CASCADE_VAD_ONSET_WINDOW_FRAMES": "VOINEY_LAB_CASCADE_VAD_ONSET_WINDOW_FRAMES",
    "CASCADE_VAD_PLAYBACK_ONSET_VOICED_FRAMES": "VOINEY_LAB_CASCADE_VAD_PLAYBACK_ONSET_VOICED_FRAMES",
    "CASCADE_VAD_PLAYBACK_ONSET_WINDOW_FRAMES": "VOINEY_LAB_CASCADE_VAD_PLAYBACK_ONSET_WINDOW_FRAMES",
    "CASCADE_VAD_PREFIX_MS": "VOINEY_LAB_CASCADE_VAD_PREFIX_MS",
    "CHAT_MODEL": "VOINEY_LAB_ANSWER_MODEL",
    "EXTERNAL_REFERENCES_ENABLED": "VOINEY_LAB_EXTERNAL_REFERENCES_ENABLED",
    "EXTERNAL_REFERENCE_ALLOWED_DOMAINS": "VOINEY_LAB_EXTERNAL_REFERENCE_ALLOWED_DOMAINS",
    "EXTERNAL_REFERENCE_CACHE_TTL_SECONDS": "VOINEY_LAB_EXTERNAL_REFERENCE_CACHE_TTL_SECONDS",
    "EXTERNAL_REFERENCE_CONNECT_TIMEOUT_SECONDS": "VOINEY_LAB_EXTERNAL_REFERENCE_CONNECT_TIMEOUT_SECONDS",
    "EXTERNAL_REFERENCE_DOMAIN_PROFILE": "VOINEY_LAB_EXTERNAL_REFERENCE_DOMAIN_PROFILE",
    "EXTERNAL_REFERENCE_ENRICHMENT_BUDGET_SECONDS": "VOINEY_LAB_EXTERNAL_REFERENCE_ENRICHMENT_BUDGET_SECONDS",
    "EXTERNAL_REFERENCE_MAX_CITATIONS": "VOINEY_LAB_EXTERNAL_REFERENCE_MAX_CITATIONS",
    "EXTERNAL_REFERENCE_MAX_TURNS": "VOINEY_LAB_EXTERNAL_REFERENCE_MAX_TURNS",
    "EXTERNAL_REFERENCE_MODEL": "VOINEY_LAB_SUPPLEMENTAL_MODEL",
    "EXTERNAL_REFERENCE_READ_TIMEOUT_SECONDS": "VOINEY_LAB_EXTERNAL_REFERENCE_READ_TIMEOUT_SECONDS",
    "EXTERNAL_REFERENCE_REASONING_EFFORT": "VOINEY_LAB_SUPPLEMENTAL_REASONING",
    "EXTERNAL_REFERENCE_SERVICE_TIER": "VOINEY_LAB_EXTERNAL_REFERENCE_SERVICE_TIER",
    "EXTERNAL_REFERENCE_TIMEOUT_SECONDS": "VOINEY_LAB_EXTERNAL_REFERENCE_TIMEOUT_SECONDS",
    "EXTERNAL_SEARCH_DISPLAY_MODE": "VOINEY_LAB_EXTERNAL_SEARCH_DISPLAY_MODE",
    "LAB_MANAGER_EMAIL": "VOINEY_LAB_LAB_MANAGER_EMAIL",
    "MOSS_INDEX_NAME": "VOINEY_LAB_MOSS_INDEX_NAME",
    "MOSS_MODEL_ID": "VOINEY_LAB_MOSS_MODEL_ID",
    "MOSS_PROJECT_ID": "VOINEY_LAB_MOSS_PROJECT_ID",
    "MOSS_PROJECT_KEY": "VOINEY_LAB_MOSS_PROJECT_KEY",
    "PLAYWRIGHT_APP_PORT": "VOINEY_LAB_PLAYWRIGHT_APP_PORT",
    "PROTOCOL_ANALYSIS_MODEL": "VOINEY_LAB_ANALYSIS_MODEL",
    "PROTOCOL_ANALYSIS_REASONING_EFFORT": "VOINEY_LAB_ANALYSIS_REASONING",
    "SUPPLEMENTAL_MODEL_KNOWLEDGE_ENABLED": "VOINEY_LAB_SUPPLEMENTAL_MODEL_KNOWLEDGE_ENABLED",
    "SUPPLEMENTAL_MODEL_KNOWLEDGE_MODEL": "VOINEY_LAB_SUPPLEMENTAL_MODEL",
    "SUPPLEMENTAL_MODEL_KNOWLEDGE_TIMEOUT_SECONDS": "VOINEY_LAB_SUPPLEMENTAL_MODEL_KNOWLEDGE_TIMEOUT_SECONDS",
    "TTS_VOICE": "VOINEY_LAB_TTS_VOICE",
    "WEB_VISUAL_SEARCH_ENABLED": "VOINEY_LAB_WEB_VISUAL_SEARCH_ENABLED",
    "WORKER_MODEL": "VOINEY_LAB_ANSWER_MODEL",
    "XAI_STT_FILLER_WORDS": "VOINEY_LAB_STT_FILLER_WORDS",
    "XAI_STT_VAD_THRESHOLD": "VOINEY_LAB_STT_VAD_THRESHOLD",
    # xAI-only voice name -> provider-neutral voice name (lane SV, 2026-10-05) (2)
    "VOINEY_LAB_XAI_STT_FILLER_WORDS": "VOINEY_LAB_STT_FILLER_WORDS",
    "VOINEY_LAB_XAI_STT_VAD_THRESHOLD": "VOINEY_LAB_STT_VAD_THRESHOLD",
    # lane M1 (decision 1, 2026-10-04): the model settings became role settings,
    # VOINEY_LAB_<ROLE>_PROVIDER / _MODEL / _REASONING (model_providers). These
    # do not follow the prefix rule; ROLE_RENAMED lists them.
    "VOINEY_LAB_LLM_ROUTER_MODEL": "VOINEY_LAB_ROUTER_MODEL",
    "VOINEY_LAB_CHAT_MODEL": "VOINEY_LAB_ANSWER_MODEL",
    "VOINEY_LAB_WORKER_MODEL": "VOINEY_LAB_ANSWER_MODEL",
    "VOINEY_LAB_MULTI_BRAIN_MODEL": "VOINEY_LAB_ANSWER_MODEL",
    "VOINEY_LAB_ANSWER_BRAIN_MODEL": "VOINEY_LAB_ANSWER_MODEL",
    "VOINEY_LAB_SOURCE_BRAIN_MODEL": "VOINEY_LAB_ANSWER_MODEL",
    "VOINEY_LAB_VISUAL_BRAIN_MODEL": "VOINEY_LAB_ANSWER_MODEL",
    "VOINEY_LAB_PROTOCOL_ANALYSIS_MODEL": "VOINEY_LAB_ANALYSIS_MODEL",
    "VOINEY_LAB_PROTOCOL_ANALYSIS_REASONING_EFFORT": "VOINEY_LAB_ANALYSIS_REASONING",
    "VOINEY_LAB_REPORT_WRITER_MODEL": "VOINEY_LAB_REPORT_MODEL",
    "VOINEY_LAB_EXTERNAL_REFERENCE_MODEL": "VOINEY_LAB_SUPPLEMENTAL_MODEL",
    "VOINEY_LAB_SUPPLEMENTAL_MODEL_KNOWLEDGE_MODEL": "VOINEY_LAB_SUPPLEMENTAL_MODEL",
    "VOINEY_LAB_EXTERNAL_REFERENCE_REASONING_EFFORT": "VOINEY_LAB_SUPPLEMENTAL_REASONING",
}

#: The old names lane M1 moved to a role setting (their new name is not the
#: old one under the new prefix).
ROLE_RENAMED: frozenset[str] = frozenset({
    "VOINEY_LAB_LLM_ROUTER_MODEL",
    "VOINEY_LAB_CHAT_MODEL",
    "VOINEY_LAB_WORKER_MODEL",
    "VOINEY_LAB_MULTI_BRAIN_MODEL",
    "VOINEY_LAB_ANSWER_BRAIN_MODEL",
    "VOINEY_LAB_SOURCE_BRAIN_MODEL",
    "VOINEY_LAB_VISUAL_BRAIN_MODEL",
    "VOINEY_LAB_PROTOCOL_ANALYSIS_MODEL",
    "VOINEY_LAB_PROTOCOL_ANALYSIS_REASONING_EFFORT",
    "VOINEY_LAB_REPORT_WRITER_MODEL",
    "VOINEY_LAB_EXTERNAL_REFERENCE_MODEL",
    "VOINEY_LAB_SUPPLEMENTAL_MODEL_KNOWLEDGE_MODEL",
    "VOINEY_LAB_EXTERNAL_REFERENCE_REASONING_EFFORT",
})


def renamed(name: str) -> str | None:
    """The new name for an old one, or None when ``name`` is not old.

    A prefixed name the table does not list still follows the prefix rule, so
    a stray old name in a ``.env`` is renamed rather than left behind.
    """

    if name in RENAMED:
        return RENAMED[name]
    if name.startswith(OLD_PREFIX) and len(name) > len(OLD_PREFIX):
        return NEW_PREFIX + name[len(OLD_PREFIX):]
    return None
